PZLinuxDarkWebItemsTable = {
    -- HUNDGUNS 
    { id = {"Base.Revolver_Short"}, Price = 375 }, 
    { id = {"Base.Pistol"}, Price = 450 },
    { id = {"Base.Pistol2"}, Price = 675 },
    { id = {"Base.Revolver"}, Price = 787 },
    { id = {"Base.Pistol3"}, Price = 750 },
    { id = {"Base.Revolver_Long"}, Price = 1000 },
    --SHOTGUNS
    { id = {"Base.DoubleBarrelShotgun"}, Price = 1500 },
    { id = {"Base.Shotgun"}, Price = 1500 },
    { id = {"Base.DoubleBarrelShotgunSawnoff"}, Price = 2100 },
    { id = {"Base.ShotgunSawnoff"}, Price = 2275 },
    -- RIFLES
    { id = {"Base.AssaultRifle"}, Price = 2000 },
    { id = {"Base.VarmintRifle"}, Price = 2000 },
    { id = {"Base.AssaultRifle2"}, Price = 2400 },
    { id = {"Base.HuntingRifle"}, Price = 2400 },
    -- AMMOS
    { id = {"Base.Bullets9mmBox"}, Price = 100},
    { id = {"Base.Bullets38Box"}, Price = 175},
    { id = {"Base.Bullets44Box"}, Price = 190},
    { id = {"Base.223Box"}, Price = 300 },
    { id = {"Base.308Box"}, Price = 300 },
    { id = {"Base.ShotgunShellsBox"}, Price = 450 },
    { id = {"Base.Bullets45Box"}, Price = 500 },
    { id = {"Base.556Box"}, Price = 600 },
    { id = {"Base.9mmClip"}, Price = 500 },
    { id = {"Base.45Clip"}, Price = 500 },
    { id = {"Base.44Clip"}, Price = 500 },
    { id = {"Base.223Clip"}, Price = 700 },
    { id = {"Base.308Clip"}, Price = 700 },
    { id = {"Base.556Clip"}, Price = 1000 },
    { id = {"Base.M14Clip"}, Price = 1000 },
    { id = {"Base.223BulletsMold"}, Price = 800 },
    { id = {"Base.308BulletsMold"}, Price = 800 },
    { id = {"Base.9mmBulletsMold"}, Price = 800 },
    { id = {"Base.ShotgunShellsMold"}, Price = 800 },
    --SCOPE
    { id = {"Base.IronSight"}, Price = 500 },
    { id = {"Base.RedDot"}, Price = 1000 },
    { id = {"Base.x8Scope"}, Price = 4000 },
    { id = {"Base.x2Scope"}, Price = 1500 },
    { id = {"Base.x4Scope"}, Price = 2000 },
    -- SLING
    { id = {"Base.AmmoStraps"}, Price = 2500 },
    -- HACKING
    { id = {"Base.IDcard_Stolen"}, Price = 1000 },
    { id = {"Base.CreditCard_Stolen"}, Price = 1000 },
    -- EXPLOSIVES
    { id = {"Base.SmokeBomb"}, Price = 100 },
    { id = {"Base.Molotov"}, Price = 150 },
    { id = {"Base.Aerosolbomb"}, Price = 150 },
    { id = {"Base.FlameTrap"}, Price = 150 },
    { id = {"Base.PipeBomb"}, Price = 150 },
    { id = {"Base.AerosolbombTriggered"}, Price = 300 },
    { id = {"Base.AerosolbombRemote"}, Price = 300 },
    -- AXES
    { id = {"Base.BaseballBat_RailSpike"}, Price = 800 },
    { id = {"Base.BaseballBat_Sawblade"}, Price = 800 },
    { id = {"Base.ScrapWeapon_Brake"}, Price = 400 },
    { id = {"Base.EntrenchingTool"}, Price = 250 },
    { id = {"Base.FieldHockeyStick_Sawblade"}, Price = 933 },
    { id = {"Base.Axe"}, Price = 533 },
    { id = {"Base.ScrapWeaponGardenFork"}, Price = 400 },
    { id = {"Base.HandScythe"}, Price = 600 },
    { id = {"Base.HandScytheForged"}, Price = 600 },
    { id = {"Base.HandAxeForged"}, Price = 350 },
    { id = {"Base.IceAxe"}, Price = 350 },
    { id = {"Base.MetalPipe_Railspike"}, Price = 400 },
    { id = {"Base.JawboneBovide_Axe"}, Price = 600 },
    { id = {"Base.LongHandle_Railspike"}, Price = 700 },
    { id = {"Base.LongHandle_Sawblade"}, Price = 700 },
    { id = {"Base.StoneAxeLarge"}, Price = 867 },
    { id = {"Base.MeatCleaverForged"}, Price = 400 },
    { id = {"Base.BaseballBat_Metal_Sawblade"}, Price = 800 },
    { id = {"Base.PickAxeForged"}, Price = 667 },
    { id = {"Base.Axe_Sawblade"}, Price = 457 },
    { id = {"Base.Axe_Sawblade_Hatchet"}, Price = 280 },
    { id = {"Base.Axe_ScrapCleaver"}, Price = 867 },
    { id = {"Base.ShortBat_RailSpike"}, Price = 533 },
    { id = {"Base.WoodAxeForged"}, Price = 867 },
    -- LONG BLUNTS
    { id = {"Base.BaseballBat_Can"}, Price = 900 },
    { id = {"Base.BaseballBat_Spiked"}, Price = 800 },
    { id = {"Base.BlockMaul"}, Price = 1000 },
    { id = {"Base.CrowbarForged"}, Price = 600 },
    { id = {"Base.BaseballBat_Metal_Bolts"}, Price = 917 },
    { id = {"Base.BaseballBat_Metal"}, Price = 800 },
    { id = {"Base.Sledgehammer"}, Price = 667 },
    --- SHORT BLUNTS
    { id = {"Base.Mace"}, Price = 280 },
    { id = {"Base.SpikedShortBat"}, Price = 300 },
    -- LONG BLADES
    { id = {"Base.CrudeShortSword"}, Price = 667 },
    { id = {"Base.CrudeSword"}, Price = 1500 },
    { id = {"Base.Katana"}, Price = 8000 },
    { id = {"Base.Machete"}, Price = 1000 },
    { id = {"Base.Machete_Crude"}, Price = 1000 },
    { id = {"Base.MacheteForged"}, Price = 1000 },
    { id = {"Base.ShortSword"}, Price = 1000 },
    { id = {"Base.Sword"}, Price = 2000 },
    -- SHORT BLADES
    { id = {"Base.FightingKnife"}, Price = 600 },
    { id = {"Base.HandguardDagger"}, Price = 600 },
    { id = {"Base.LargeKnife"}, Price = 600 },
    { id = {"Base.KnifeParing"}, Price = 600 },
    { id = {"Base.HuntingKnife"}, Price = 600 },
    { id = {"Base.KitchenKnife"}, Price = 600 },
    { id = {"Base.KitchenKnifeForged"}, Price = 600 },
    { id = {"Base.HuntingKnifeForged"}, Price = 600 },
    { id = {"Base.KnifePocket"}, Price = 800 },
    -- SPEARS
    { id = {"Base.SpearLong"}, Price = 444 },
    { id = {"Base.SpearShort"}, Price = 417 },
    -- RECIPES
    { id = {"Base.TailoringMag9"}, Price = 500 },
    { id = {"Base.SmithingMag8"}, Price = 500 },
    { id = {"Base.FarmingMag5"}, Price = 500 },
    { id = {"Base.TailoringMag1"}, Price = 500 },
    { id = {"Base.FishingMag1"}, Price = 500 },
    { id = {"Base.FishingMag2"}, Price = 500 },
    { id = {"Base.ArmorMag5"}, Price = 1000 },
    { id = {"Base.WeaponMag4"}, Price = 2000 },
    { id = {"Base.FarmingMag3"}, Price = 500 },
    { id = {"Base.SmithingMag5"}, Price = 500 },
    { id = {"Base.GlassmakingMag3"}, Price = 500 },
    { id = {"Base.GlassmakingMag2"}, Price = 500 },
    { id = {"Base.TailoringMag5"}, Price = 500 },
    { id = {"Base.FarmingMag6"}, Price = 500 },
    { id = {"Base.PrimitiveToolMag2"}, Price = 500 },
    { id = {"Base.CookingMag6"}, Price = 500 },
    { id = {"Base.ArmorMag2"}, Price = 1000 },
    { id = {"Base.ArmorMag4"}, Price = 1000 },
    { id = {"Base.SmithingMag3"}, Price = 500 },
    { id = {"Base.SmithingMag1"}, Price = 500 },
    { id = {"Base.SmithingMag2"}, Price = 500 },
    { id = {"Base.ArmorMag7"}, Price = 1000 },
    { id = {"Base.TailoringMag7"}, Price = 500 },
    { id = {"Base.HuntingMag4"}, Price = 500 },
    { id = {"Base.CookingMag1"}, Price = 500 },
    { id = {"Base.CookingMag2"}, Price = 500 },
    { id = {"Base.CookingMag4"}, Price = 500 },
    { id = {"Base.FarmingMag7"}, Price = 500 },
    { id = {"Base.RadioMag1"}, Price = 500 },
    { id = {"Base.RadioMag3"}, Price = 500 },
    { id = {"Base.FarmingMag9"}, Price = 500 },
    { id = {"Base.ElectronicsMag3"}, Price = 500 },
    { id = {"Base.TailoringMag10"}, Price = 500 },
    { id = {"Base.ElectronicsMag4"}, Price = 5000 },
    { id = {"Base.SmithingMag9"}, Price = 500 },
    { id = {"Base.CookingMag3"}, Price = 500 },
    { id = {"Base.FarmingMag1"}, Price = 500 },
    { id = {"Base.FarmingMag2"}, Price = 500 },
    { id = {"Base.MechanicMag2"}, Price = 2000 },
    { id = {"Base.MechanicMag3"}, Price = 2000 },
    { id = {"Base.MechanicMag1"}, Price = 2000 },
    { id = {"Base.TailoringMag4"}, Price = 500 },
    { id = {"Base.HempMag1"}, Price = 500 },
    { id = {"Base.ElectronicsMag2"}, Price = 500 },
    { id = {"Base.SmithingMag7"}, Price = 500 },
    { id = {"Base.SmithingMag11"}, Price = 500 },
    { id = {"Base.SmithingMag10"}, Price = 500 },
    { id = {"Base.TailoringMag3"}, Price = 500 },
    { id = {"Base.SmithingMag6"}, Price = 500 },
    { id = {"Base.GlassmakingMag1"}, Price = 500 },
    { id = {"Base.WeaponMag2"}, Price = 2000 },
    { id = {"Base.TailoringMag8"}, Price = 500 },
    { id = {"Base.ArmorMag1"}, Price = 1000 },
    { id = {"Base.PrimitiveToolMag3"}, Price = 500 },
    { id = {"Base.TailoringMag2"}, Price = 500 },
    { id = {"Base.TailoringMag6"}, Price = 500 },
    { id = {"Base.EngineerMagazine1"}, Price = 500 },
    { id = {"Base.TrickMag1"}, Price = 500 },
    { id = {"Base.WeaponMag6"}, Price = 2000 },
    { id = {"Base.ArmorMag3"}, Price = 1000 },
    { id = {"Base.HuntingMag1"}, Price = 500 },
    { id = {"Base.SmithingMag4"}, Price = 500 },
    { id = {"Base.ElectronicsMag5"}, Price = 500 },
    { id = {"Base.RadioMag2"}, Price = 500 },
    { id = {"Base.ArmorMag6"}, Price = 1000 },
    { id = {"Base.EngineerMagazine2"}, Price = 500 },
    { id = {"Base.KeyMag1"}, Price = 500 },
    { id = {"Base.TrickMag2"}, Price = 500 },
    { id = {"Base.EngineerMagazine3"}, Price = 500 },
    { id = {"Base.WeaponMag3"}, Price = 2000 },
    { id = {"Base.WeaponMag5"}, Price = 2000 },
    { id = {"Base.FarmingMag4"}, Price = 500 },
    { id = {"Base.WeaponMag1"}, Price = 2000 },
    { id = {"Base.HuntingMag2"}, Price = 500 },
    { id = {"Base.WeaponMag7"}, Price = 2000 },
    { id = {"Base.FarmingMag8"}, Price = 500 },
    { id = {"Base.PrimitiveToolMag1"}, Price = 500 },
    { id = {"Base.MetalworkMag3"}, Price = 500 },
    { id = {"Base.MetalworkMag1"}, Price = 500 },
    { id = {"Base.MetalworkMag4"}, Price = 500 },
    { id = {"Base.MetalworkMag2"}, Price = 500 },
    { id = {"Base.HerbalistMag"}, Price = 500 },
    { id = {"Base.HuntingMag3"}, Price = 500 },
    { id = {"Base.KnittingMag1"}, Price = 500 },
    { id = {"Base.KnittingMag2"}, Price = 500 },
    { id = {"Base.CookingMag5"}, Price = 500 },
    { id = {"Base.ElectronicsMag1"}, Price = 500 },
    -- BOOK
    { id = {"Base.BookFarming1"}, Price = 100 },
    { id = {"Base.BookFarming2"}, Price = 200 },
    { id = {"Base.BookFarming3"}, Price = 300 },
    { id = {"Base.BookFarming4"}, Price = 400 },
    { id = {"Base.BookFarming5"}, Price = 500 },
    { id = {"Base.BookAiming1"}, Price = 100 },
    { id = {"Base.BookAiming2"}, Price = 200 },
    { id = {"Base.BookAiming3"}, Price = 300 },
    { id = {"Base.BookAiming4"}, Price = 400 },
    { id = {"Base.BookAiming5"}, Price = 500 },
    { id = {"Base.BookHusbandry1"}, Price = 100 },
    { id = {"Base.BookHusbandry2"}, Price = 200 },
    { id = {"Base.BookHusbandry3"}, Price = 300 },
    { id = {"Base.BookHusbandry4"}, Price = 400 },
    { id = {"Base.BookHusbandry5"}, Price = 500 },
    { id = {"Base.BookBlacksmith1"}, Price = 100 },
    { id = {"Base.BookBlacksmith2"}, Price = 200 },
    { id = {"Base.BookBlacksmith3"}, Price = 300 },
    { id = {"Base.BookBlacksmith4"}, Price = 400 },
    { id = {"Base.BookBlacksmith5"}, Price = 500 },
    { id = {"Base.BookButchering1"}, Price = 100 },
    { id = {"Base.BookButchering2"}, Price = 200 },
    { id = {"Base.BookButchering3"}, Price = 300 },
    { id = {"Base.BookButchering4"}, Price = 400 },
    { id = {"Base.BookButchering5"}, Price = 500 },
    { id = {"Base.BookCarpentry1"}, Price = 100 },
    { id = {"Base.BookCarpentry2"}, Price = 200 },
    { id = {"Base.BookCarpentry3"}, Price = 300 },
    { id = {"Base.BookCarpentry4"}, Price = 400 },
    { id = {"Base.BookCarpentry5"}, Price = 500 },
    { id = {"Base.BookCarving1"}, Price = 100 },
    { id = {"Base.BookCarving2"}, Price = 200 },
    { id = {"Base.BookCarving3"}, Price = 300 },
    { id = {"Base.BookCarving4"}, Price = 400 },
    { id = {"Base.BookCarving5"}, Price = 500 },
    { id = {"Base.BookCooking1"}, Price = 100 },
    { id = {"Base.BookCooking2"}, Price = 200 },
    { id = {"Base.BookCooking3"}, Price = 300 },
    { id = {"Base.BookCooking4"}, Price = 400 },
    { id = {"Base.BookCooking5"}, Price = 500 },
    { id = {"Base.BookElectrician1"}, Price = 100 },
    { id = {"Base.BookElectrician2"}, Price = 200 },
    { id = {"Base.BookElectrician3"}, Price = 300 },
    { id = {"Base.BookElectrician4"}, Price = 400 },
    { id = {"Base.BookElectrician5"}, Price = 500 },
    { id = {"Base.BookFirstAid1"}, Price = 100 },
    { id = {"Base.BookFirstAid2"}, Price = 200 },
    { id = {"Base.BookFirstAid3"}, Price = 300 },
    { id = {"Base.BookFirstAid4"}, Price = 400 },
    { id = {"Base.BookFirstAid5"}, Price = 500 },
    { id = {"Base.BookFishing1"}, Price = 100 },
    { id = {"Base.BookFishing2"}, Price = 200 },
    { id = {"Base.BookFishing3"}, Price = 300 },
    { id = {"Base.BookFishing4"}, Price = 400 },
    { id = {"Base.BookFishing5"}, Price = 500 },
    { id = {"Base.BookForaging1"}, Price = 100 },
    { id = {"Base.BookForaging2"}, Price = 200 },
    { id = {"Base.BookForaging3"}, Price = 300 },
    { id = {"Base.BookForaging4"}, Price = 400 },
    { id = {"Base.BookForaging5"}, Price = 500 },
    { id = {"Base.BookGlassmaking1"}, Price = 100 },
    { id = {"Base.BookGlassmaking2"}, Price = 200 },
    { id = {"Base.BookGlassmaking3"}, Price = 300 },
    { id = {"Base.BookGlassmaking4"}, Price = 400 },
    { id = {"Base.BookGlassmaking5"}, Price = 500 },
    { id = {"Base.BookFlintKnapping1"}, Price = 100 },
    { id = {"Base.BookFlintKnapping2"}, Price = 200 },
    { id = {"Base.BookFlintKnapping3"}, Price = 300 },
    { id = {"Base.BookFlintKnapping4"}, Price = 400 },
    { id = {"Base.BookFlintKnapping5"}, Pric2 = 500 },
    { id = {"Base.BookLongBlade1"}, Price = 100 },
    { id = {"Base.BookLongBlade2"}, Price = 200 },
    { id = {"Base.BookLongBlade3"}, Price = 300 },
    { id = {"Base.BookLongBlade4"}, Price = 400 },
    { id = {"Base.BookLongBlade5"}, Price = 500 },
    { id = {"Base.BookMaintenance1"}, Price = 100 },
    { id = {"Base.BookMaintenance2"}, Price = 200 },
    { id = {"Base.BookMaintenance3"}, Price = 300 },
    { id = {"Base.BookMaintenance4"}, Price = 400 },
    { id = {"Base.BookMaintenance5"}, Pric2 = 500 },
    { id = {"Base.BookMasonry1"}, Price = 100 },
    { id = {"Base.BookMasonry2"}, Price = 200 },
    { id = {"Base.BookMasonry3"}, Price = 300 },
    { id = {"Base.BookMasonry4"}, Price = 400 },
    { id = {"Base.BookMasonry5"}, Price = 500 },
    { id = {"Base.BookMechanic1"}, Price = 100 },
    { id = {"Base.BookMechanic2"}, Price = 200 },
    { id = {"Base.BookMechanic3"}, Price = 300 },
    { id = {"Base.BookMechanic4"}, Price = 400 },
    { id = {"Base.BookMechanic5"}, Price = 500 },
    { id = {"Base.BookPottery1"}, Price = 100 },
    { id = {"Base.BookPottery2"}, Price = 200 },
    { id = {"Base.BookPottery3"}, Price = 300 },
    { id = {"Base.BookPottery4"}, Price = 400 },
    { id = {"Base.BookPottery5"}, Price = 500 },
    { id = {"Base.BookReloading1"}, Price = 100 },
    { id = {"Base.BookReloading2"}, Price = 200 },
    { id = {"Base.BookReloading3"}, Price = 300 },
    { id = {"Base.BookReloading4"}, Price = 400 },
    { id = {"Base.BookReloading5"}, Price = 500 },
    { id = {"Base.BookTailoring1"}, Price = 100 },
    { id = {"Base.BookTailoring2"}, Price = 200 },
    { id = {"Base.BookTailoring3"}, Price = 300 },
    { id = {"Base.BookTailoring4"}, Price = 400 },
    { id = {"Base.BookTailoring5"}, Price = 500 },
    { id = {"Base.BookTracking1"}, Price = 100 },
    { id = {"Base.BookTracking2"}, Price = 200 },
    { id = {"Base.BookTracking3"}, Price = 300 },
    { id = {"Base.BookTracking4"}, Price = 400 },
    { id = {"Base.BookTracking5"}, Price = 500 },
    { id = {"Base.BookTrapping1"}, Price = 100 },
    { id = {"Base.BookTrapping2"}, Price = 200 },
    { id = {"Base.BookTrapping3"}, Price = 300 },
    { id = {"Base.BookTrapping4"}, Price = 400 },
    { id = {"Base.BookTrapping5"}, Price = 500 },
    { id = {"Base.BookMetalWelding1"}, Price = 100 },
    { id = {"Base.BookMetalWelding2"}, Price = 200 },
    { id = {"Base.BookMetalWelding3"}, Price = 300 },
    { id = {"Base.BookMetalWelding4"}, Price = 400 },
    { id = {"Base.BookMetalWelding5"}, Price = 500 },
    -- MEDICAL
    { id = {"Base.Antibiotics"}, Price = 1500 },
    { id = {"Base.PillsAntiDep"}, Price = 500 },
    { id = {"Base.PillsBeta"}, Price = 500 },
    { id = {"Base.Pills"}, Price = 100 },
    { id = {"Base.PillsSleepingTablets"}, Price = 200 },
    { id = {"Base.PillsVitamins"}, Price = 100 },
    { id = {"Base.CigaretteSingle"}, Price = 10 },
    { id = {"Base.CigarettePack"}, Price = 200 },
    { id = {"Base.CigaretteCarton"}, Price = 2000 },
    { id = {"Base.Cigar"}, Price = 200 },
    -- EQUIPMENT
    { id = {"Base.Bag_ALICEpack_Army"}, Price = 2000 },
    -- VEHICLE
    { id = {"Base.PetrolCan"}, Price = 3000 },
    -- ELECTRONICS
    { id = {"Base.Generator_Yellow"}, Price = 6000 },
    { id = {"Base.Generator"}, Price = 5000 },
    { id = {"Base.Generator_Blue"}, Price = 4000 },
    { id = {"Base.Generator_Old"}, Price = 3500 },
    { id = {"Base.RemoteCraftedV3"}, Price = 400 },
    { id = {"Base.RemoteCraftedV2"}, Price = 300 },
    { id = {"Base.RemoteCraftedV1"}, Price = 200 },
    { id = {"Base.ScannerModule"}, Price = 100 },
    { id = {"Base.ElectronicsScrap"}, Price = 50 },
    { id = {"Base.Amplifier"}, Price = 50 },
    { id = {"Base.RadioReceiver"}, Price = 50 },
    { id = {"Base.RadioTransmitter"}, Price = 50 },
    { id = {"Base.Receiver"}, Price = 50 },
    -- BAR/INGOT
    { id = {"Base.PigIronIngot"}, Price = 100 },
    { id = {"Base.BrassIngot"}, Price = 500 },
    { id = {"Base.CopperIngot"}, Price = 600 },
    { id = {"Base.SteelIngot"}, Price = 1000 },
    { id = {"Base.SilverBar"}, Price = 5000 },
    { id = {"Base.GoldBar"}, Price = 15000 },
    -- CLOTHING
    { id = {"Base.Socks_Heavy"}, Price = 50 },
    { id = {"Base.Socks_Long"}, Price = 50},
    { id = {"Base.Socks_Long_White"}, Price = 50 },
    { id = {"Base.Socks_Long_Black"}, Price = 50 },
    { id = {"Base.Socks_Ankle"}, Price = 50 }, 
    { id = {"Base.Socks_Ankle_White"}, Price = 50 },
    { id = {"Base.Socks_Ankle_Black"}, Price = 50 },
    { id = {"Base.Bra_Straps_AnimalPrint"}, Price = 100 },
    { id = {"Base.Bra_Straps_FrillyBlack"}, Price = 100 },
    { id = {"Base.Bra_Straps_Black"}, Price = 100 },
    { id = {"Base.Bra_Straps_FrillyPink"}, Price = 100 },
    { id = {"Base.Bra_Straps_FrillyRed"}, Price = 100 },
    { id = {"Base.Bra_Straps_Hide"}, Price = 100 },
    { id = {"Base.Bra_Strapless_AnimalPrint"}, Price = 100 },
    { id = {"Base.Bra_Strapless_FrillyBlack"}, Price = 100 },
    { id = {"Base.Bra_Strapless_Black"}, Price = 100 },
    { id = {"Base.Bra_Strapless_FrillyPink"}, Price = 100 },
    { id = {"Base.Bra_Strapless_FrillyRed"}, Price = 100 },
    { id = {"Base.Bra_Strapless_RedSpots"}, Price = 100 },
    { id = {"Base.Bra_Strapless_Hide"}, Price = 100 },
    { id = {"Base.Bra_Strapless_White"}, Price = 100 },
    { id = {"Base.Bra_Straps_White"}, Price = 100 },
    { id = {"Base.Bikini_Pattern01"}, Price = 150 },
    { id = {"Base.Briefs_SmallTrunks_Black"}, Price = 200 },
    { id = {"Base.Briefs_SmallTrunks_Blue"}, Price = 200 },
    { id = {"Base.Briefs_SmallTrunks_Red"}, Price = 200 },
    { id = {"Base.Underpants_AnimalPrint"}, Price = 200 },
    { id = {"Base.FrillyUnderpants_Black"}, Price = 200 },
    { id = {"Base.Underpants_Black"}, Price = 200 },
    { id = {"Base.FrillyUnderpants_Pink"}, Price = 200 },
    { id = {"Base.FrillyUnderpants_Red"}, Price = 200 },
    { id = {"Base.Underpants_RedSpots"}, Price = 200 },
    { id = {"Base.Underpants_Hide"}, Price = 200 },
    { id = {"Base.Underpants_White"}, Price = 200 },
    -- ARMOR
    { id = {"Base.Hat_Beret"}, Price = 500 },
    { id = {"Base.Hat_BalaclavaFull"}, Price = 500 },
    { id = {"Base.Hat_Police"}, Price = 500 },
    { id = {"Base.Hat_Army"}, Price = 1000 },
    { id = {"Base.Hat_ArmyDesertNew"}, Price = 1000 },
    { id = {"Base.Hat_ArmyDesert"}, Price = 1000 },
    { id = {"Base.Hat_CrashHelmet_Police"}, Price = 1000 },
    { id = {"Base.Hat_RiotHelmet"}, Price = 1000 },
    { id = {"Base.Hat_ArmyWWII"}, Price = 1000 },
    { id = {"Base.Hat_SPHhelmet"}, Price = 1000 },
    { id = {"Base.ShinKneeGuard_L_Metal", "Base.ShinKneeGuard_R_Metal"}, Price = 1000 },
    { id = {"Base.Shoulderpad_Articulated_L_Metal", "Base.Shoulderpad_Articulated_R_Metal"}, Price = 1000 }, 
    { id = {"Base.Thigh_ArticMetal_R", "Base.Thigh_ArticMetal_L"}, Price = 1000 }, 
    { id = {"Base.ElbowPad_Right_Tactical"}, Price = 1000 },
    { id = {"Base.Vambrace_BodyArmour_Left_Army"}, Price = 1000 },
    { id = {"Base.GreaveBodyArmour_Right_Army"}, Price = 1000 },
    { id = {"Base.Shoes_ArmyBoots"}, Price = 1000 },
    { id = {"Base.Shoes_ArmyBootsDesert"}, Price = 1000 },
    { id = {"Base.Shoulderpad_MetalScrap_L", "Base.Shoulderpad_MetalScrap_R"}, Price = 1500 },
    { id = {"Base.Hat_GasMask_nofilter"}, Price = 1500 },
    { id = {"Base.Chainmail_SleeveFull_L", "Base.Chainmail_SleeveFull_R"}, Price = 2000 }, 
    { id = {"Base.Hat_GasMask"}, Price = 2000 },
    { id = {"Base.Vest_BulletArmy"}, Price = 5000 }, 
    { id = {"Base.Vest_BulletPolice"}, Price = 5000 }, 
    { id = {"Base.Vest_BulletSWAT"}, Price = 5000 },
    -- GOLD
    { id = {"Base.Medal_Bronze"}, Price = 100 },
    { id = {"Base.Medal_Gold"}, Price = 500 },
    { id = {"Base.Medal_Silver"}, Price = 250 },
    { id = {"Base.Necklace_Gold"}, Price = 600 },
    { id = {"Base.Necklace_GoldDiamond"}, Price = 800 },
    { id = {"Base.Necklace_GoldRuby"}, Price = 650 },
    { id = {"Base.Necklace_Silver"}, Price = 300 },
    { id = {"Base.Necklace_SilverCrucifix"}, Price = 250 },
    { id = {"Base.Necklace_SilverDiamond"}, Price = 150 },
    { id = {"Base.Necklace_SilverSapphire"}, Price = 200 },
    { id = {"Base.Necklace_YingYang"}, Price = 10 },
    { id = {"Base.NecklaceLong_Amber"}, Price = 50 },
    { id = {"Base.NecklaceLong_GoldDiamond"}, Price = 1000, },
    { id = {"Base.NecklaceLong_Gold"}, Price = 850, },
    { id = {"Base.NecklaceLong_SilverDiamond"}, Price = 450 },
    { id = {"Base.NecklaceLong_SilverEmerald"}, Price = 450 },
    { id = {"Base.NecklaceLong_SilverSapphire"}, Price = 450 },
    { id = {"Base.NecklaceLong_Silver"}, Price = 250 },
    { id = {"Base.NoseRing_Gold"}, Price = 100, },
    { id = {"Base.NoseRing_Silver"}, Price = 50 },
    { id = {"Base.NoseStud_Gold"}, Price = 80, },
    { id = {"Base.NoseStud_Silver"}, Price = 40 },
    { id = {"Base.Earring_Dangly_Diamond"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Emerald"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Pearl"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Ruby"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Sapphire"}, Price = 100, },
    { id = {"Base.Earring_Stone_Emerald"}, Price = 100, },
    { id = {"Base.Earring_Stud_Gold"}, Price = 250, },
    { id = {"Base.Earring_LoopLrg_Gold"}, Price = 250, },
    { id = {"Base.Earring_LoopLrg_Silver"}, Price = 80 },
    { id = {"Base.Earring_LoopMed_Gold"}, Price = 100, },
    { id = {"Base.Earring_LoopMed_Silver"}, Price = 80 },
    { id = {"Base.Earring_Pearl"}, Price = 60, },
    { id = {"Base.Earring_Stone_Ruby"}, Price = 60, },
    { id = {"Base.Earring_Stone_Sapphire"}, Price = 60, },
    { id = {"Base.Earring_Stud_Silver"}, Price = 50 },
    { id = {"Base.Earring_LoopSmall_Gold_Both", "Base.Earring_LoopSmall_Gold_Top"}, Price = 50, },
    { id = {"Base.Earring_LoopSmall_Silver_Both", "Base.Earring_LoopSmall_Silver_Top"}, Price = 50, },
    { id = {"Base.Bracelet_BangleRightGold", "Base.Bracelet_BangleLeftGold"}, Price = 300 },
    { id = {"Base.Bracelet_BangleRightSilver", "Base.Bracelet_BangleLeftSilver"}, Price = 250 },
    { id = {"Base.Bracelet_ChainRightGold", "Base.Bracelet_ChainLeftGold"}, Price = 250 },
    { id = {"Base.Bracelet_ChainRightSilver", "Base.Bracelet_ChainLeftSilver"}, Price = 150 },
    { id = {"Base.WristWatch_Right_ClassicGold", "Base.WristWatch_Left_ClassicGold"}, Price = 1500 },
    { id = {"WristWatch_Right_Expensive", "Base.WristWatch_Left_Expensive"}, Price = 1500 },
    { id = {"Base.Ring_Right_MiddleFinger_GoldDiamond", "Base.Ring_Left_MiddleFinger_GoldDiamond", "Base.Ring_Right_RingFinger_GoldDiamond", "Base.Ring_Left_RingFinger_GoldDiamond"}, Price = 500 },
    { id = {"Base.Ring_Right_MiddleFinger_GoldRuby", "Base.Ring_Left_MiddleFinger_GoldRuby", "Base.Ring_Right_RingFinger_GoldRuby", "Base.Ring_Left_RingFinger_GoldRuby"}, Price = 500 },
    { id = {"Base.Ring_Right_MiddleFinger_Gold", "Base.Ring_Left_MiddleFinger_Gold", "Base.Ring_Right_RingFinger_Gold","Base.Ring_Left_RingFinger_Gold"}, Price = 500 },
    { id = {"Base.Ring_Right_MiddleFinger_SilverDiamond", "Base.Ring_Left_MiddleFinger_SilverDiamond", "Base.Ring_Right_RingFinger_SilverDiamond", "Base.Ring_Left_RingFinger_SilverDiamond"}, Price = 300 },
    { id = {"Base.Ring_Right_MiddleFinger_Silver", "Base.Ring_Left_MiddleFinger_Silver", "Base.Ring_Right_RingFinger_Silver", "Base.Ring_Left_RingFinger_Silver"}, Price = 300 },
    { id = {"Base.BellyButton_DangleGoldRuby"}, Price = 150 },
    { id = {"Base.BellyButton_DangleGold"}, Price = 250 },
    { id = {"Base.BellyButton_DangleSilverDiamond"}, Price = 150 },
    { id = {"Base.BellyButton_DangleSilver"}, Price = 50 },
    { id = {"Base.BellyButton_RingGoldDiamond"}, Price = 150 },
    { id = {"Base.BellyButton_RingGoldRuby"}, Price = 150 },
    { id = {"Base.BellyButton_RingGold"}, Price = 250 },
    { id = {"Base.BellyButton_RingSilverAmethyst"}, Price = 75 },
    { id = {"Base.BellyButton_RingSilverDiamond"}, Price = 75 },
    { id = {"Base.BellyButton_RingSilverRuby"}, Price = 75 },
    { id = {"Base.BellyButton_RingSilver"}, Price = 50 },
    { id = {"Base.BellyButton_StudGoldDiamond"}, Price = 150 },
    { id = {"Base.BellyButton_StudGold"}, Price = 150 },
    { id = {"Base.BellyButton_StudSilverDiamond"}, Price = 75 },
    { id = {"Base.BellyButton_StudSilver"}, Price = 50 }
}

PZLinuxTradingCompanyNameTable = {
    { name = "Crisis Commerce Corp", code = "CCC", price = 1450 },
    { name = "Umbrella Corp", code = "AC", price = 1400 },
    { name = "Walker & Crawler", code = "WC", price = 1300 },
    { name = "Survival Solutions Inc", code = "SSI", price = 1200 },
    { name = "Reclaim Resources Ltd", code = "RRL", price = 1110 },
    { name = "Brain Beers Times", code = "BBT", price = 1000 },
    { name = "Zom Bin", code = "ZB", price = 950 },
    { name = "Endurance Equipments", code = "EE", price = 850 },
    { name = "Grinning Grim Goods", code = "GGG", price = 610 },
    { name = "Country Court Outlaw", code = "CCO", price = 580 },
    { name = "ZomboTrade Co", code = "ZTC", price = 560 },
    { name = "COVID Pop Ltd", code = "CPL", price = 500 },
    { name = "Gorrest Fump", code = "GF", price = 450 },
    { name = "Phoenix Resupply Corp", code = "PRC", price = 350 },
    { name = "Heaven Saint Christ", code = "HSC", price = 260 },
    { name = "28 Ways to Stay Safe", code = "WSS", price = 245 },
    { name = "The Hunger Z", code = "THZ", price = 235 },
    { name = "Zombie of the rings", code = "ZOR", price = 220 },
    { name = "Zombie Zumba", code = "ZZ", price = 200 },
    { name = "Indoor Adventures", code = "IA", price = 180 },
    { name = "Pandemic Pills Inc", code = "PPI", price = 170 },
    { name = "Aftermath Trading Post", code = "ATP", price = 160 },
    { name = "Waste Not Industries", code = "WNI", price = 120 },
    { name = "NecroTech Innovations", code = "NTI", price = 80 },
    { name = "Z Max", code = "ZM", price = 65 },
    { name = "Vigilant Ventures", code = "VV", price = 40 },
    { name = "Flee Market", code = "FM", price = 30 },
    { name = "Raven Goods & Supply", code = "RGS", price = 25 },
    { name = "Brains & Bargains", code = "BB", price = 20 },
    { name = "Rot & Roll", code = "RR", price = 10 },
    { name = "Butcher Ltd", code = "BL", price = 5 }
}

function generateUsername()
    local prefixes = {"Xx", "Dark", "Neo", "Cyber", "Red", "Blue", "Fire", "Frost", "Shadow", "Ghost"}
    local suffixes = {"99", "77", "Pro", "X", "V2", "Elite", "Bot", "Z", "Master", "King"}
    local middle = {"_", ".", ""}

    local name = prefixes[ZombRand(1, #prefixes + 1)] ..
                 middle[ZombRand(1, #middle + 1)] ..
                 suffixes[ZombRand(1, #suffixes + 1)]
    
    return name
end

function PZLinuxGenerateRandomName()
    local names = {
        { id = 1, first = "Jame", last = "Smith" },
        { id = 2, first = "Mary", last = "Johnson" },
        { id = 3, first = "Robert", last = "Williams" },
        { id = 4, first = "Patricia", last = "Brown" },
        { id = 5, first = "John", last = "Jones" },
        { id = 6, first = "Jennifer", last = "Garcia" },
        { id = 7, first = "Michael", last = "Miller" },
        { id = 8, first = "Linda", last = "Davis" },
        { id = 9, first = "William", last = "Rodriguez" },
        { id = 10, first = "Elizabeth", last = "Martinez" },
        { id = 11, first = "David", last = "Hernandez" },
        { id = 12, first = "Barbara", last = "Lopez" },
        { id = 13, first = "Richard", last = "Gonzalez" },
        { id = 14, first = "Susan", last = "Wilson" },
        { id = 15, first = "Joseph", last = "Anderson" },
        { id = 16, first = "Jessica", last = "Thomas" },
        { id = 17, first = "Thomas", last = "Taylor" },
        { id = 18, first = "Sarah", last = "Moore" },
        { id = 19, first = "Charles", last = "Jackson" },
        { id = 20, first = "Karen", last = "Martin" },
        { id = 21, first = "Christopher", last = "Lee" },
        { id = 22, first = "Nancy", last = "Perez" },
        { id = 23, first = "Daniel", last = "Thompson" },
        { id = 24, first = "Betty", last = "White" },
        { id = 25, first = "Matthew", last = "Harris" },
        { id = 26, first = "Sandra", last = "Sanchez" },
        { id = 27, first = "Anthony", last = "Clark" },
        { id = 28, first = "Ashley", last = "Ramirez" },
        { id = 29, first = "Mark", last = "Lewis" },
        { id = 30, first = "Donna", last = "Robinson" },
        { id = 31, first = "Paul", last = "Walker" },
        { id = 32, first = "Emily", last = "Young" },
        { id = 33, first = "Steven", last = "Allen" },
        { id = 34, first = "Stephanie", last = "King" },
        { id = 35, first = "Andrew", last = "Wright" },
        { id = 36, first = "Melissa", last = "Scott" },
        { id = 37, first = "Kenneth", last = "Torres" },
        { id = 38, first = "Amy", last = "Nguyen" },
        { id = 39, first = "Joshua", last = "Hill" },
        { id = 40, first = "Angela", last = "Flores" },
        { id = 41, first = "Kevin", last = "Green" },
        { id = 42, first = "Sharon", last = "Adams" },
        { id = 43, first = "Brian", last = "Nelson" },
        { id = 44, first = "Laura", last = "Baker" },
        { id = 45, first = "George", last = "Hall" },
        { id = 46, first = "Kimberly", last = "Rivera" },
        { id = 47, first = "Edward", last = "Campbell" },
        { id = 48, first = "Deborah", last = "Mitchell" },
        { id = 49, first = "Jason", last = "Carter" },
        { id = 50, first = "Michelle", last = "Roberts" },
        { id = 51, first = "Jeffrey", last = "Gomez" },
        { id = 52, first = "Emily", last = "Phillips" },
        { id = 53, first = "Ryan", last = "Evans" },
        { id = 54, first = "Carol", last = "Turner" },
        { id = 55, first = "Jacob", last = "Diaz" },
        { id = 56, first = "Rebecca", last = "Parker" },
        { id = 57, first = "Gary", last = "Edwards" },
        { id = 58, first = "Cynthia", last = "Collins" },
        { id = 59, first = "Nicholas", last = "Stewart" },
        { id = 60, first = "Kathleen", last = "Morris" },
        { id = 61, first = "Eric", last = "Rogers" },
        { id = 62, first = "Shirley", last = "Reed" },
        { id = 63, first = "Stephen", last = "Cook" },
        { id = 64, first = "Anna", last = "Morgan" },
        { id = 65, first = "Jonathan", last = "Bell" },
        { id = 66, first = "Brenda", last = "Murphy" },
        { id = 67, first = "Larry", last = "Bailey" },
        { id = 68, first = "Emma", last = "Rivera" },
        { id = 69, first = "Justin", last = "Cooper" },
        { id = 70, first = "Pamela", last = "Richardson" },
        { id = 71, first = "Scott", last = "Cox" },
        { id = 72, first = "Nicole", last = "Howard" },
        { id = 73, first = "Brandon", last = "Ward" },
        { id = 74, first = "Megan", last = "Torres" },
        { id = 75, first = "Benjamin", last = "Peterson" },
        { id = 76, first = "Julie", last = "Gray" },
        { id = 77, first = "Samuel", last = "Ramirez" },
        { id = 78, first = "Hannah", last = "James" },
        { id = 79, first = "Gregory", last = "Watson" },
        { id = 80, first = "Victoria", last = "Brooks" },
        { id = 81, first = "Frank", last = "Kelly" },
        { id = 82, first = "Olivia", last = "Sanders" },
        { id = 83, first = "Alexander", last = "Price" },
        { id = 84, first = "Christina", last = "Bennett" },
        { id = 85, first = "Raymond", last = "Wood" },
        { id = 86, first = "Diane", last = "Barnes" },
        { id = 87, first = "Patrick", last = "Ross" },
        { id = 88, first = "Evelyn", last = "Henderson" },
        { id = 89, first = "Jack", last = "Coleman" },
        { id = 90, first = "Rachel", last = "Jenkins" },
        { id = 91, first = "Dennis", last = "Perry" },
        { id = 92, first = "Grace", last = "Powell" },
        { id = 93, first = "Jerry", last = "Long" },
        { id = 94, first = "Lauren", last = "Patterson" },
        { id = 95, first = "Tyler", last = "Hughes" },
        { id = 96, first = "Alice", last = "Flores" },
        { id = 97, first = "Aaron", last = "Washington" },
        { id = 98, first = "Jacqueline", last = "Butler" },
        { id = 99, first = "Jose", last = "Simmons" },
        { id = 100, first = "Katherine", last = "Foster" },
    }
    local firstNameId = ZombRand(#names) + 1
    local lastNameId  = ZombRand(#names) + 1
    local targetName = names[firstNameId].first .. " " .. names[lastNameId].last
    return targetName
end

PZLinuxMailTable = {
    { baseName = "CONGRATULATIONS!", type = "ads"},
    { baseName = "THE WINNER IS", type = "ads"},
    { baseName = "HOLIDAY FOR FREE", type = "ads"},
    { baseName = "Need Ammo", type = "ammo"},
    { baseName = "Medical supplies", type = "medical"},
}