PZLinux = PZLinux or {}

PZLinuxRaceRunnerPool = PZLinuxRaceRunnerPool or {
    { name = "Gallop Zomb", rating = 2, maxRating = 10 },
    { name = "The Great Gallopino", rating = 2, maxRating = 10 },
    { name = "Zombplay", rating = 2, maxRating = 15 },
    { name = "AppleJack", rating = 2, maxRating = 15 },
    { name = "Hocus Pocus", rating = 2, maxRating = 15 },
    { name = "Mr Ed", rating = 2, maxRating = 15 },
    { name = "Whinny the Poop", rating = 2, maxRating = 15 },
    { name = "Long Drop Face", rating = 2, maxRating = 15 },
    { name = "Eyes Out", rating = 2, maxRating = 15 },
    { name = "Smell Bad", rating = 2, maxRating = 15 },
    { name = "Crawler Texas Ranger", rating = 2, maxRating = 15 },
    { name = "Walk to the Moon", rating = 2, maxRating = 15 },
    { name = "Never Sleep Again", rating = 2, maxRating = 15 },
    { name = "Tobit or not Tobit", rating = 2, maxRating = 15 },
    { name = "Toothless", rating = 2, maxRating = 20 },
    { name = "Barefoot", rating = 2, maxRating = 20 },
    { name = "Always Hungry", rating = 2, maxRating = 20 },
    { name = "Eat This", rating = 2, maxRating = 20 },
    { name = "Horde", rating = 2, maxRating = 20 },
    { name = "Toc toc toc", rating = 2, maxRating = 20 },
    { name = "I have Maggots", rating = 2, maxRating = 20 },
    { name = "Glenn", rating = 2, maxRating = 20 },
    { name = "Alpha", rating = 2, maxRating = 20 },
    { name = "A Zomb With No Name", rating = 2, maxRating = 20 },
    { name = "Nobody", rating = 2, maxRating = 20 },
    { name = "No Arms no Chocolate", rating = 2, maxRating = 20 },
    { name = "Zomby McZombyface", rating = 2, maxRating = 20 },
    { name = "Biscuit", rating = 2, maxRating = 20 },
    { name = "Zomby Jumper", rating = 2, maxRating = 20 },
    { name = "Rainbow Rider", rating = 2, maxRating = 20 },
    { name = "Fuzzy Wuzzy", rating = 2, maxRating = 50 },
    { name = "Tony Spark", rating = 2, maxRating = 50 },
    { name = "Thannos", rating = 2, maxRating = 50 },
    { name = "Worm", rating = 2, maxRating = 50 },
    { name = "Should be the wind", rating = 2, maxRating = 50 },
    { name = "Machu Pichtou", rating = 2, maxRating = 50 },
    { name = "Sponge Zomb", rating = 2, maxRating = 100 },
    { name = "Jean Cloud", rating = 2, maxRating = 100 },
    { name = "The King is dead", rating = 2, maxRating = 100 },
    { name = "Terminathour", rating = 2, maxRating = 100 },
}
