PZLinux = PZLinux or {}

PZLinuxRaceRunnerPool = PZLinuxRaceRunnerPool or {
    { name = "Ash Runner", rating = 2, maxRating = 10 },
    { name = "Raven Creek", rating = 2, maxRating = 10 },
    { name = "Dust Walker", rating = 2, maxRating = 15 },
    { name = "Cold Track", rating = 2, maxRating = 15 },
    { name = "Red Mile", rating = 2, maxRating = 15 },
    { name = "Night Signal", rating = 2, maxRating = 15 },
    { name = "Grave Pace", rating = 2, maxRating = 15 },
    { name = "Long Road", rating = 2, maxRating = 15 },
    { name = "Dead Sprint", rating = 2, maxRating = 15 },
    { name = "Bad Omen", rating = 2, maxRating = 15 },
    { name = "County Line", rating = 2, maxRating = 15 },
    { name = "Moon Walker", rating = 2, maxRating = 15 },
    { name = "Sleepless", rating = 2, maxRating = 15 },
    { name = "Last Turn", rating = 2, maxRating = 15 },
    { name = "Broken Shoes", rating = 2, maxRating = 20 },
    { name = "Bare Bones", rating = 2, maxRating = 20 },
    { name = "Hungry Road", rating = 2, maxRating = 20 },
    { name = "Final Bite", rating = 2, maxRating = 20 },
    { name = "South Horde", rating = 2, maxRating = 20 },
    { name = "Door Knock", rating = 2, maxRating = 20 },
    { name = "Rotten Luck", rating = 2, maxRating = 20 },
    { name = "Green River", rating = 2, maxRating = 20 },
    { name = "Alpha Rot", rating = 2, maxRating = 20 },
    { name = "Nameless", rating = 2, maxRating = 20 },
    { name = "No Witness", rating = 2, maxRating = 20 },
    { name = "Lost Arms", rating = 2, maxRating = 20 },
    { name = "Old Shambler", rating = 2, maxRating = 20 },
    { name = "Backstreet", rating = 2, maxRating = 20 },
    { name = "Fence Jumper", rating = 2, maxRating = 20 },
    { name = "Storm Rider", rating = 2, maxRating = 20 },
    { name = "Fever Dream", rating = 2, maxRating = 50 },
    { name = "Spark Plug", rating = 2, maxRating = 50 },
    { name = "Ash King", rating = 2, maxRating = 50 },
    { name = "Wormwood", rating = 2, maxRating = 50 },
    { name = "Headwind", rating = 2, maxRating = 50 },
    { name = "Pine Ridge", rating = 2, maxRating = 50 },
    { name = "Blue Rot", rating = 2, maxRating = 100 },
    { name = "Cloud Cover", rating = 2, maxRating = 100 },
    { name = "Crown Fall", rating = 2, maxRating = 100 },
    { name = "Last Hour", rating = 2, maxRating = 100 },
}
