PZLinux = PZLinux or {}

PZLinuxRequestDefinitions = PZLinuxRequestDefinitions or {
    [1] = { baseName = "Canned food", price = 750, items = {"Base.TinnedBeans", "Base.CannedCarrots2", "Base.CannedChili", "Base.CannedCorn", "Base.CannedCornedBeef", "Base.CannedMushroomSoup", "Base.CannedPeaches", "Base.CannedPeas", "Base.CannedPineapple", "Base.CannedPotato2", "Base.CannedSardines", "Base.TinnedSoup", "Base.CannedBolognese", "Base.CannedTomato2", "Base.TunaTin", "Base.Dogfood", "Base.CannedMilk", "Base.CannedFruitBeverage"} },
    [2] = { baseName = "Meat", price = 1000, items = {"Base.Baloney", "Base.Chicken", "Base.Ham", "Base.MincedMeat", "Base.MuttonChop", "Base.PorkChop", "Base.Salami", "Base.Sausage", "Base.Steak"} },
    [3] = { baseName = "Fish", price = 1500, items = {"Base.Paddlefish", "Base.FlatheadCatfish", "Base.ChannelCatfish", "Base.BlueCatfish", "Base.BlackCrappie", "Base.Bluegill", "Base.Shrimp", "Base.FreshwaterDrum", "Base.Muskellunge", "Base.SmallmouthBass", "Base.StripedBass", "Base.WhiteBass", "Base.YellowPerch"} },
    [4] = { baseName = "Fruits", price = 500, items = {"Base.Apple", "Base.Banana", "Base.BerryBlack", "Base.BerryBlue", "Base.Cherry", "Base.Grapes", "Base.Lemon", "Base.Lime", "Base.Mango", "Base.Orange", "Base.Peach", "Base.Pear", "Base.Pineapple", "Base.Watermelon"} },
    [5] = { baseName = "Vegetables", price = 500, items = {"Base.Avocado", "Base.BellPepper", "Base.Blackbeans", "Base.Broccoli", "Base.Carrots", "Base.Corn", "Base.Daikon", "Base.Edamame", "Base.Eggplant", "Base.PepperHabanero", "Base.PepperJalapeno", "Base.Leek", "Base.Lettuce", "Base.Onion", "Base.Pickles", "Base.Pumpkin", "Base.Zucchini"} },
    [6] = { baseName = "Pickled food", price = 950, items = {"Base.CannedBellPepper", "Base.CannedBroccoli", "Base.CannedCabbage", "Base.CannedCarrots", "Base.CannedEggplant", "Base.CannedLeek", "Base.CannedPotato", "Base.CannedRedRadish", "Base.CannedTomato"} },
    [7] = { baseName = "Drink", price = 1000, items = {"Base.JuiceBox", "Base.Milk", "Base.PopBottle", "Base.Pop2", "Base.Pop", "Base.Pop3"} },
    [8] = { baseName = "Book", price = 800, items = {"Base.Book", "Base.Magazine"} },
    [9] = { baseName = "Car", price = 65000, vehicles = {
        { baseName = "Base.CarStationWagon", delta = 1.2 }, { baseName = "Base.CarStationWagon2", delta = 1.2 }, { baseName = "Base.SportsCar", delta = 4 }, { baseName = "Base.PickUpTruck", delta = 2 }, { baseName = "Base.PickUpTruckLightsFire", delta = 2.5 }, { baseName = "Base.PickUpTruckMccoy", delta = 2 }, { baseName = "Base.SmallCar", delta = 0.5 }, { baseName = "Base.CarNormal", delta = 1 }, { baseName = "Base.CarLightsPolice", delta = 2 }, { baseName = "Base.CarTaxi", delta = 1 }, { baseName = "Base.CarTaxi2", delta = 1 }, { baseName = "Base.ModernCar02", delta = 1.5 }, { baseName = "Base.StepVan", delta = 1.8 }, { baseName = "Base.StepVanMail", delta = 1.8 }, { baseName = "Base.StepVan_Heralds", delta = 1.8 }, { baseName = "Base.StepVan_Scarlet", delta = 1.8 }, { baseName = "Base.ModernCar", delta = 1.5 }, { baseName = "Base.OffRoad", delta = 3 }, { baseName = "Base.SUV", delta = 3 }, { baseName = "Base.Van", delta = 2 }, { baseName = "Base.VanAmbulance", delta = 2.5 }, { baseName = "Base.VanRadio", delta = 2 }, { baseName = "Base.VanSeats", delta = 2 }, { baseName = "Base.VanRadio_3N", delta = 2 }, { baseName = "Base.VanSpiffo", delta = 2 }, { baseName = "Base.Van_KnoxDisti", delta = 2 }, { baseName = "Base.Van_LectroMax", delta = 2 }, { baseName = "Base.Van_MassGenFac", delta = 2 }, { baseName = "Base.Van_Transit", delta = 2 }, { baseName = "Base.SmallCar02", delta = 0.5 }, { baseName = "Base.CarLuxury", delta = 4 }
    } },
    [10] = { baseName = "Repairing", price = 700, items = {"Base.Scotchtape", "Base.DuctTape", "Base.Glue", "Base.Woodglue"} },
    [11] = { baseName = "Materials", price = 650, items = {"Base.Aluminum", "Base.ConcretePowder", "Base.PlasterPowder", "Base.BarbedWire", "Base.NailsBox", "Base.PaperclipBox", "Base.Screws", "Base.Sparklers", "Base.Charcoal", "Base.Dirtbag", "Base.Hinge", "Base.Doorknob", "Base.Gravelbag", "Base.GunPowder", "Base.SheetMetal", "Base.Nails", "Base.Plank", "Base.PropaneTank", "Base.Rope", "Base.SmallSheetMetal", "Base.Staples", "Base.Stone", "Base.Tarp", "Base.Thread", "Base.Twine", "Base.WeldingRods", "Base.Wire", "Base.Yarn", "Base.DenimStrips", "Base.LeatherStrips", "Base.RippedSheets"} },
    [12] = { baseName = "Paint bucket", price = 450, items = {"Base.PaintBlack", "Base.PaintBlue", "Base.PaintBrown", "Base.PaintCyan", "Base.PaintGreen", "Base.PaintGrey", "Base.PaintLightBlue", "Base.PaintLightBrown", "Base.PaintOrange", "Base.PaintPink", "Base.PaintPurple", "Base.PaintRed", "Base.PaintTurquoise", "Base.PaintWhite", "Base.PaintYellow", "Base.PaintbucketEmpty"} },
    [13] = { baseName = "Electronics", price = 900, items = {"Base.Battery", "Base.Amplifier", "Base.TimerCrafted", "Base.TriggerCrafted", "Base.ElectricWire", "Base.ElectronicsScrap", "Base.MotionSensor", "Base.RadioReceiver", "Base.RadioTransmitter", "Base.Receiver", "Base.ScannerModule", "Base.RemoteCraftedV1", "Base.RemoteCraftedV2", "Base.RemoteCraftedV3", "Base.LightBulb", "Base.LightBulbRed", "Base.LightBulbGreen", "Base.LightBulbBlue", "Base.LightBulbYellow", "Base.LightBulbCyan", "Base.LightBulbMagenta", "Base.LightBulbOrange", "Base.LightBulbPurple", "Base.LightBulbPink"} },
    [14] = { baseName = "Seeds", price = 300, items = {"Base.RoseBagSeed", "Base.PoppyBagSeed", "Base.LavenderBagSeed", "Base.BarleyBagSeed", "Base.RyeBagSeed", "Base.SugarBeetBagSeed", "Base.WheatBagSeed", "Base.ChamomileBagSeed", "Base.MarigoldBagSeed", "Base.LettuceBagSeed", "Base.BellPepperBagSeed", "Base.CauliflowerBagSeed", "Base.CucumberBagSeed", "Base.LeekBagSeed", "Base.LemonGrassBagSeed", "Base.ZucchiniBagSeed", "Base.WatermelonBagSeed", "Base.HabaneroBagSeed", "Base.JalapenoBagSeed", "Base.BlackSageBagSeed", "Base.BroadleafPlantainBagSeed", "Base.ComfreyBagSeed", "Base.CommonMallowBagSeed", "Base.HempBagSeed", "Base.HopsBagSeed", "Base.MintBagSeed", "Base.TurnipBagSeed", "Base.WildGarlicBagSeed", "Base.PumpkinBagSeed"} },
}

PZLinuxRequestVehicleLocations = PZLinuxRequestVehicleLocations or {
    { name = "Storage Units of Riverside", x = 5550, y = 6080, z = 0 },
    { name = "Storage Units of Brandenburg", x = 1995, y = 6519, z = 0 },
    { name = "Storage Units of Irvington", x = 2442, y = 13917, z = 0 },
    { name = "Storage Units of Muldraugh: South", x = 10771, y = 10323, z = 0 },
    { name = "Storage Units of Muldraugh: North", x = 10696, y = 9814, z = 0 },
    { name = "Storage Units of West Point", x = 12154, y = 6996, z = 0 },
    { name = "Storage Units of Valley Station", x = 12963, y = 4851, z = 0 },
    { name = "Storage Units of Louisville: South", x = 12712, y = 2010, z = 0 },
    { name = "Storage Units of Louisville: West", x = 12205, y = 1684, z = 0 },
}
