PZLinuxContractTargetNames = PZLinuxContractTargetNames or {
    { first = "Jame", last = "Smith" },
    { first = "Mary", last = "Johnson" },
    { first = "Robert", last = "Williams" },
    { first = "Patricia", last = "Brown" },
    { first = "John", last = "Jones" },
    { first = "Jennifer", last = "Garcia" },
    { first = "Michael", last = "Miller" },
    { first = "Linda", last = "Davis" },
    { first = "William", last = "Rodriguez" },
    { first = "Elizabeth", last = "Martinez" },
    { first = "David", last = "Hernandez" },
    { first = "Barbara", last = "Lopez" },
    { first = "Richard", last = "Gonzalez" },
    { first = "Susan", last = "Wilson" },
    { first = "Joseph", last = "Anderson" },
    { first = "Jessica", last = "Thomas" },
    { first = "Thomas", last = "Taylor" },
    { first = "Sarah", last = "Moore" },
    { first = "Charles", last = "Jackson" },
    { first = "Karen", last = "Martin" },
    { first = "Christopher", last = "Lee" },
    { first = "Nancy", last = "Perez" },
    { first = "Daniel", last = "Thompson" },
    { first = "Betty", last = "White" },
    { first = "Matthew", last = "Harris" },
    { first = "Sandra", last = "Sanchez" },
    { first = "Anthony", last = "Clark" },
    { first = "Ashley", last = "Ramirez" },
    { first = "Mark", last = "Lewis" },
    { first = "Donna", last = "Robinson" },
    { first = "Paul", last = "Walker" },
    { first = "Emily", last = "Young" },
    { first = "Steven", last = "Allen" },
    { first = "Stephanie", last = "King" },
    { first = "Andrew", last = "Wright" },
    { first = "Melissa", last = "Scott" },
    { first = "Kenneth", last = "Torres" },
    { first = "Amy", last = "Nguyen" },
    { first = "Joshua", last = "Hill" },
    { first = "Angela", last = "Flores" },
    { first = "Kevin", last = "Green" },
    { first = "Sharon", last = "Adams" },
    { first = "Brian", last = "Nelson" },
    { first = "Laura", last = "Baker" },
    { first = "George", last = "Hall" },
    { first = "Kimberly", last = "Rivera" },
    { first = "Edward", last = "Campbell" },
    { first = "Deborah", last = "Mitchell" },
    { first = "Jason", last = "Carter" },
    { first = "Michelle", last = "Roberts" },
    { first = "Jeffrey", last = "Gomez" },
    { first = "Emily", last = "Phillips" },
    { first = "Ryan", last = "Evans" },
    { first = "Carol", last = "Turner" },
    { first = "Jacob", last = "Diaz" },
    { first = "Rebecca", last = "Parker" },
    { first = "Gary", last = "Edwards" },
    { first = "Cynthia", last = "Collins" },
    { first = "Nicholas", last = "Stewart" },
    { first = "Kathleen", last = "Morris" },
    { first = "Eric", last = "Rogers" },
    { first = "Shirley", last = "Reed" },
    { first = "Stephen", last = "Cook" },
    { first = "Anna", last = "Morgan" },
    { first = "Jonathan", last = "Bell" },
    { first = "Brenda", last = "Murphy" },
    { first = "Larry", last = "Bailey" },
    { first = "Emma", last = "Rivera" },
    { first = "Justin", last = "Cooper" },
    { first = "Pamela", last = "Richardson" },
    { first = "Scott", last = "Cox" },
    { first = "Nicole", last = "Howard" },
    { first = "Brandon", last = "Ward" },
    { first = "Megan", last = "Torres" },
    { first = "Benjamin", last = "Peterson" },
    { first = "Julie", last = "Gray" },
    { first = "Samuel", last = "Ramirez" },
    { first = "Hannah", last = "James" },
    { first = "Gregory", last = "Watson" },
    { first = "Victoria", last = "Brooks" },
    { first = "Frank", last = "Kelly" },
    { first = "Olivia", last = "Sanders" },
    { first = "Alexander", last = "Price" },
    { first = "Christina", last = "Bennett" },
    { first = "Raymond", last = "Wood" },
    { first = "Diane", last = "Barnes" },
    { first = "Patrick", last = "Ross" },
    { first = "Evelyn", last = "Henderson" },
    { first = "Jack", last = "Coleman" },
    { first = "Rachel", last = "Jenkins" },
    { first = "Dennis", last = "Perry" },
    { first = "Grace", last = "Powell" },
    { first = "Jerry", last = "Long" },
    { first = "Lauren", last = "Patterson" },
    { first = "Tyler", last = "Hughes" },
    { first = "Alice", last = "Flores" },
    { first = "Aaron", last = "Washington" },
    { first = "Jacqueline", last = "Butler" },
    { first = "Jose", last = "Simmons" },
    { first = "Katherine", last = "Foster" },
}

function PZLinuxContractsRandomTargetName()
    local firstName = PZLinuxContractTargetNames[ZombRand(1, #PZLinuxContractTargetNames + 1)]
    local lastName = PZLinuxContractTargetNames[ZombRand(1, #PZLinuxContractTargetNames + 1)]
    return firstName.first .. " " .. lastName.last
end

PZLinuxContractAutoPartRequests = PZLinuxContractAutoPartRequests or {
    { baseName = "Base.CarBattery3", name = "Battery: Resistant", delta = 1 },
    { baseName = "Base.CarBattery2", name = "Battery: Sport", delta = 0.9 },
    { baseName = "Base.CarBattery1", name = "Battery: Standard", delta = 0.8 },
    { baseName = "Base.ModernBrake3", name = "Performance brakes: Resistant", delta = 1 },
    { baseName = "Base.ModernBrake2", name = "Performance brakes: Sport", delta = 0.9 },
    { baseName = "Base.ModernBrake1", name = "Performance brakes: Standard", delta = 0.8 },
    { baseName = "Base.ModernCarMuffler3", name = "Performance silencers: Resistant", delta = 1 },
    { baseName = "Base.ModernCarMuffler2", name = "Performance silencers: Sport", delta = 0.9 },
    { baseName = "Base.ModernCarMuffler1", name = "Performance silencers: Standard", delta = 0.8 },
    { baseName = "Base.ModernSuspension3", name = "Performance suspension: Resistant", delta = 1 },
    { baseName = "Base.ModernSuspension2", name = "Performance suspension: Sport", delta = 0.9 },
    { baseName = "Base.ModernSuspension1", name = "Performance suspension: Standard", delta = 0.8 },
    { baseName = "Base.NormalBrake3", name = "Standard brakes: Resistant", delta = 0.7 },
    { baseName = "Base.NormalBrake2", name = "Standard brakes: Sport", delta = 0.6 },
    { baseName = "Base.NormalBrake1", name = "Standard brakes: Standard", delta = 0.5 },
    { baseName = "Base.NormalCarMuffler3", name = "Standard silencers: Resistant", delta = 0.7 },
    { baseName = "Base.NormalCarMuffler2", name = "Standard silencers: Sport", delta = 0.6 },
    { baseName = "Base.NormalCarMuffler1", name = "Standard silencers: Standard", delta = 0.5 },
    { baseName = "Base.NormalSuspension3", name = "Standard suspension: Resistant", delta = 0.7 },
    { baseName = "Base.NormalSuspension2", name = "Standard suspension: Sport", delta = 0.6 },
    { baseName = "Base.NormalSuspension1", name = "Standard suspension: Standard", delta = 0.5 },
}

function PZLinuxContractsRandomAutoPartRequest()
    return PZLinuxContractAutoPartRequests[ZombRand(1, #PZLinuxContractAutoPartRequests + 1)]
end

PZLinuxContractMedicalRequests = PZLinuxContractMedicalRequests or {
    { baseName = "Base.Bandaid", name = "Bandage: Adhesive", delta = 0.5 },
    { baseName = "Base.Bandage", name = "Bandage", delta = 0.6 },
    { baseName = "Base.AlcoholWipes", name = "Alcohol Wipes", delta = 0.8 },
    { baseName = "Base.Disinfectant", name = "Bottle of Disinfectant", delta = 1.2 },
    { baseName = "Base.AlcoholedCottonBalls", name = "Cotton Balls Doused in Alcohol", delta = 0.7 },
    { baseName = "Base.Antibiotics", name = "Antibiotics", delta = 1.5 },
    { baseName = "Base.PillsAntiDep", name = "Antidepressants", delta = 1.1 },
    { baseName = "Base.PillsBeta", name = "Beta Blockers", delta = 1 },
    { baseName = "Base.Pills", name = "Painkillers", delta = 1.3 },
    { baseName = "Base.PillsSleepingTablets", name = "Sleeping Pills", delta = 0.8 },
    { baseName = "Base.PillsVitamins", name = "Caffeine Pills", delta = 0.7 },
}

function PZLinuxContractsRandomMedicalRequest()
    return PZLinuxContractMedicalRequests[ZombRand(1, #PZLinuxContractMedicalRequests + 1)]
end

PZLinuxContractWeaponRequests = PZLinuxContractWeaponRequests or {
    { baseName = "Base.Pistol3", name = "D-E Pistol", delta = 0.3 },
    { baseName = "Base.Pistol2", name = "M1911 Pistol", delta = 0.3 },
    { baseName = "Base.Revolver_Short", name = "M36 Revolver", delta = 0.5 },
    { baseName = "Base.Revolver", name = "M625 Revolver", delta = 0.4 },
    { baseName = "Base.Pistol", name = "M9 Pistol", delta = 0.3 },
    { baseName = "Base.Revolver_Long", name = "Magnum", delta = 0.5 },
    { baseName = "Base.DoubleBarrelShotgun", name = "Double Barrel Shotgun", delta = 1.2 },
    { baseName = "Base.Shotgun", name = "JS-2000 Shotgun", delta = 1.2 },
    { baseName = "Base.DoubleBarrelShotgunSawnoff", name = "Sawed-off Double Barrel Shotgun", delta = 1.2 },
    { baseName = "Base.ShotgunSawnoff", name = "Sawed-off JS-2000 Shotgun", delta = 1.2 },
    { baseName = "Base.AssaultRifle2", name = "M14 Rifle", delta = 1.5 },
    { baseName = "Base.AssaultRifle", name = "M16 Assault Rifle", delta = 1.5 },
    { baseName = "Base.VarmintRifle", name = "MSR700 Rifle", delta = 1.5 },
    { baseName = "Base.HuntingRifle", name = "MSR788 Rifle", delta = 1.5 },
}

function PZLinuxContractsRandomWeaponRequest()
    return PZLinuxContractWeaponRequests[ZombRand(1, #PZLinuxContractWeaponRequests + 1)]
end
