PZLinux = PZLinux or {}

PZLinuxTradingCompanyNameTable = {
    { name = "Crisis Commerce Corp", code = "CCC", price = 1450 },
    { name = "Umbrella Corp", code = "AC", price = 1400 },
    { name = "Walker & Crawler", code = "WC", price = 1300 },
    { name = "Survival Solutions Inc", code = "SSI", price = 1200 },
    { name = "Reclaim Resources Ltd", code = "RRL", price = 1110 },
    { name = "Brain Beers Times", code = "BBT", price = 1000 },
    { name = "Zom Bin", code = "ZB", price = 950 },
    { name = "Endurance Equipments", code = "EE", price = 850 },
    { name = "Grinning Grim Goods", code = "GGG", price = 610 },
    { name = "Country Court Outlaw", code = "CCO", price = 580 },
    { name = "ZomboTrade Co", code = "ZTC", price = 560 },
    { name = "COVID Pop Ltd", code = "CPL", price = 500 },
    { name = "Gorrest Fump", code = "GF", price = 450 },
    { name = "Phoenix Resupply Corp", code = "PRC", price = 350 },
    { name = "Heaven Saint Christ", code = "HSC", price = 260 },
    { name = "28 Ways to Stay Safe", code = "WSS", price = 245 },
    { name = "The Hunger Z", code = "THZ", price = 235 },
    { name = "Zombie of the rings", code = "ZOR", price = 220 },
    { name = "Zombie Zumba", code = "ZZ", price = 200 },
    { name = "Indoor Adventures", code = "IA", price = 180 },
    { name = "Pandemic Pills Inc", code = "PPI", price = 170 },
    { name = "Aftermath Trading Post", code = "ATP", price = 160 },
    { name = "Waste Not Industries", code = "WNI", price = 120 },
    { name = "NecroTech Innovations", code = "NTI", price = 80 },
    { name = "Z Max", code = "ZM", price = 65 },
    { name = "Vigilant Ventures", code = "VV", price = 40 },
    { name = "Flee Market", code = "FM", price = 30 },
    { name = "Raven Goods & Supply", code = "RGS", price = 25 },
    { name = "Brains & Bargains", code = "BB", price = 20 },
    { name = "Rot & Roll", code = "RR", price = 10 },
    { name = "Butcher Ltd", code = "BL", price = 5 }
}
