PZLinuxDarkWebItemsTable = {
    -- HUNDGUNS 
    { id = {"Base.Revolver_Short"}, Price = 375 }, 
    { id = {"Base.Pistol"}, Price = 450 },
    { id = {"Base.Pistol2"}, Price = 675 },
    { id = {"Base.Revolver"}, Price = 787 },
    { id = {"Base.Pistol3"}, Price = 750 },
    { id = {"Base.Revolver_Long"}, Price = 1000 },
    --SHOTGUNS
    { id = {"Base.DoubleBarrelShotgun"}, Price = 1500 },
    { id = {"Base.Shotgun"}, Price = 1500 },
    { id = {"Base.DoubleBarrelShotgunSawnoff"}, Price = 2100 },
    { id = {"Base.ShotgunSawnoff"}, Price = 2275 },
    -- RIFLES
    { id = {"Base.AssaultRifle"}, Price = 2000 },
    { id = {"Base.VarmintRifle"}, Price = 2000 },
    { id = {"Base.AssaultRifle2"}, Price = 2400 },
    { id = {"Base.HuntingRifle"}, Price = 2400 },
    -- AMMOS
    { id = {"Base.Bullets9mmBox"}, Price = 100},
    { id = {"Base.Bullets38Box"}, Price = 175},
    { id = {"Base.Bullets44Box"}, Price = 190},
    { id = {"Base.223Box"}, Price = 300 },
    { id = {"Base.308Box"}, Price = 300 },
    { id = {"Base.ShotgunShellsBox"}, Price = 450 },
    { id = {"Base.Bullets45Box"}, Price = 500 },
    { id = {"Base.556Box"}, Price = 600 },
    { id = {"Base.9mmClip"}, Price = 500 },
    { id = {"Base.45Clip"}, Price = 500 },
    { id = {"Base.44Clip"}, Price = 500 },
    { id = {"Base.223Clip"}, Price = 700 },
    { id = {"Base.308Clip"}, Price = 700 },
    { id = {"Base.556Clip"}, Price = 1000 },
    { id = {"Base.M14Clip"}, Price = 1000 },
    { id = {"Base.223BulletsMold"}, Price = 800 },
    { id = {"Base.308BulletsMold"}, Price = 800 },
    { id = {"Base.9mmBulletsMold"}, Price = 800 },
    { id = {"Base.ShotgunShellsMold"}, Price = 800 },
    --SCOPE
    { id = {"Base.IronSight"}, Price = 500 },
    { id = {"Base.RedDot"}, Price = 1000 },
    { id = {"Base.x8Scope"}, Price = 4000 },
    { id = {"Base.x2Scope"}, Price = 1500 },
    { id = {"Base.x4Scope"}, Price = 2000 },
    -- SLING
    { id = {"Base.AmmoStraps"}, Price = 2500 },
    -- HACKING
    { id = {"Base.IDcard_Stolen"}, Price = 1000 },
    { id = {"Base.CreditCard_Stolen"}, Price = 1000 },
    -- EXPLOSIVES
    { id = {"Base.SmokeBomb"}, Price = 100 },
    { id = {"Base.Molotov"}, Price = 150 },
    { id = {"Base.Aerosolbomb"}, Price = 150 },
    { id = {"Base.FlameTrap"}, Price = 150 },
    { id = {"Base.PipeBomb"}, Price = 150 },
    { id = {"Base.AerosolbombTriggered"}, Price = 300 },
    { id = {"Base.AerosolbombRemote"}, Price = 300 },
    -- AXES
    { id = {"Base.BaseballBat_RailSpike"}, Price = 800 },
    { id = {"Base.BaseballBat_Sawblade"}, Price = 800 },
    { id = {"Base.ScrapWeapon_Brake"}, Price = 400 },
    { id = {"Base.EntrenchingTool"}, Price = 250 },
    { id = {"Base.FieldHockeyStick_Sawblade"}, Price = 933 },
    { id = {"Base.Axe"}, Price = 533 },
    { id = {"Base.ScrapWeaponGardenFork"}, Price = 400 },
    { id = {"Base.HandScythe"}, Price = 600 },
    { id = {"Base.HandScytheForged"}, Price = 600 },
    { id = {"Base.HandAxeForged"}, Price = 350 },
    { id = {"Base.IceAxe"}, Price = 350 },
    { id = {"Base.MetalPipe_Railspike"}, Price = 400 },
    { id = {"Base.JawboneBovide_Axe"}, Price = 600 },
    { id = {"Base.LongHandle_Railspike"}, Price = 700 },
    { id = {"Base.LongHandle_Sawblade"}, Price = 700 },
    { id = {"Base.StoneAxeLarge"}, Price = 867 },
    { id = {"Base.MeatCleaverForged"}, Price = 400 },
    { id = {"Base.BaseballBat_Metal_Sawblade"}, Price = 800 },
    { id = {"Base.PickAxeForged"}, Price = 667 },
    { id = {"Base.Axe_Sawblade"}, Price = 457 },
    { id = {"Base.Axe_Sawblade_Hatchet"}, Price = 280 },
    { id = {"Base.Axe_ScrapCleaver"}, Price = 867 },
    { id = {"Base.ShortBat_RailSpike"}, Price = 533 },
    { id = {"Base.WoodAxeForged"}, Price = 867 },
    -- LONG BLUNTS
    { id = {"Base.BaseballBat_Can"}, Price = 900 },
    { id = {"Base.BaseballBat_Spiked"}, Price = 800 },
    { id = {"Base.BlockMaul"}, Price = 1000 },
    { id = {"Base.CrowbarForged"}, Price = 600 },
    { id = {"Base.BaseballBat_Metal_Bolts"}, Price = 917 },
    { id = {"Base.BaseballBat_Metal"}, Price = 800 },
    { id = {"Base.Sledgehammer"}, Price = 667 },
    --- SHORT BLUNTS
    { id = {"Base.Mace"}, Price = 280 },
    { id = {"Base.SpikedShortBat"}, Price = 300 },
    -- LONG BLADES
    { id = {"Base.CrudeShortSword"}, Price = 667 },
    { id = {"Base.CrudeSword"}, Price = 1500 },
    { id = {"Base.Katana"}, Price = 8000 },
    { id = {"Base.Machete"}, Price = 1000 },
    { id = {"Base.Machete_Crude"}, Price = 1000 },
    { id = {"Base.MacheteForged"}, Price = 1000 },
    { id = {"Base.ShortSword"}, Price = 1000 },
    { id = {"Base.Sword"}, Price = 2000 },
    -- SHORT BLADES
    { id = {"Base.FightingKnife"}, Price = 600 },
    { id = {"Base.HandguardDagger"}, Price = 600 },
    { id = {"Base.LargeKnife"}, Price = 600 },
    { id = {"Base.KnifeParing"}, Price = 600 },
    { id = {"Base.HuntingKnife"}, Price = 600 },
    { id = {"Base.KitchenKnife"}, Price = 600 },
    { id = {"Base.KitchenKnifeForged"}, Price = 600 },
    { id = {"Base.HuntingKnifeForged"}, Price = 600 },
    { id = {"Base.KnifePocket"}, Price = 800 },
    -- SPEARS
    { id = {"Base.SpearLong"}, Price = 444 },
    { id = {"Base.SpearShort"}, Price = 417 },
    -- RECIPES
    { id = {"Base.SmithingMag8"}, Price = 500 },
    { id = {"Base.ArmorMag5"}, Price = 500 },
    { id = {"Base.WeaponMag4"}, Price = 500 },
    { id = {"Base.SmithingMag5"}, Price = 500 },
    { id = {"Base.ArmorMag2"}, Price = 500 },
    { id = {"Base.ArmorMag4"}, Price = 500 },
    { id = {"Base.ArmorMag7"}, Price = 500 },
    { id = {"Base.ElectronicsMag3"}, Price = 500 },
    { id = {"Base.ElectronicsMag4"}, Price = 500 },
    { id = {"Base.ElectronicsMag2"}, Price = 500 },
    { id = {"Base.SmithingMag7"}, Price = 500 },
    { id = {"Base.ArmorMag3"}, Price = 500 },
    { id = {"Base.ArmorMag6"}, Price = 500 },
    { id = {"Base.EngineerMagazine2"}, Price = 500 },
    { id = {"Base.WeaponMag5"}, Price = 500 },
    { id = {"Base.PrimitiveToolMag1"}, Price = 500 },
    { id = {"Base.ElectronicsMag1"}, Price = 500 },
    { id = {"Base.ArmorSchematic"}, Price = 500 },
    { id = {"Base.ExplosiveSchematic"}, Price = 500 },
    { id = {"Base.MeleeWeaponSchematic"}, Price = 500 },
    -- MEDICAL
    { id = {"Base.Antibiotics"}, Price = 1500 },
    { id = {"Base.PillsAntiDep"}, Price = 500 },
    { id = {"Base.PillsBeta"}, Price = 500 },
    { id = {"Base.Pills"}, Price = 100 },
    { id = {"Base.PillsSleepingTablets"}, Price = 200 },
    { id = {"Base.PillsVitamins"}, Price = 100 },
    { id = {"Base.CigarettePack"}, Price = 50 },
    { id = {"Base.CigaretteCarton"}, Price = 500 },
    { id = {"Base.CigarBox"}, Price = 1000 },
    -- EQUIPMENT
    { id = {"Base.Bag_ALICEpack_Army"}, Price = 2000 },
    -- VEHICLE
    { id = {"Base.PetrolCan"}, Price = 3000 },
    -- ELECTRONICS
    { id = {"Base.Generator"}, Price = 5000 },
    { id = {"Base.ElectronicsScrap"}, Price = 50 },
    -- BAR/INGOT
    { id = {"Base.PigIronIngot"}, Price = 100 },
    { id = {"Base.BrassIngot"}, Price = 500 },
    { id = {"Base.CopperIngot"}, Price = 600 },
    { id = {"Base.SteelIngot"}, Price = 1000 },
    { id = {"Base.SilverBar"}, Price = 5000 },
    { id = {"Base.GoldBar"}, Price = 15000 },
    -- CLOTHING
    { id = {"Base.Socks_Heavy"}, Price = 50 },
    { id = {"Base.Socks_Long"}, Price = 50},
    { id = {"Base.Socks_Long_White"}, Price = 50 },
    { id = {"Base.Socks_Long_Black"}, Price = 50 },
    { id = {"Base.Socks_Ankle"}, Price = 50 }, 
    { id = {"Base.Socks_Ankle_White"}, Price = 50 },
    { id = {"Base.Socks_Ankle_Black"}, Price = 50 },
    { id = {"Base.Bra_Straps_AnimalPrint"}, Price = 100 },
    { id = {"Base.Bra_Straps_FrillyBlack"}, Price = 100 },
    { id = {"Base.Bra_Straps_Black"}, Price = 100 },
    { id = {"Base.Bra_Straps_FrillyPink"}, Price = 100 },
    { id = {"Base.Bra_Straps_FrillyRed"}, Price = 100 },
    { id = {"Base.Bra_Straps_Hide"}, Price = 100 },
    { id = {"Base.Bra_Strapless_AnimalPrint"}, Price = 100 },
    { id = {"Base.Bra_Strapless_FrillyBlack"}, Price = 100 },
    { id = {"Base.Bra_Strapless_Black"}, Price = 100 },
    { id = {"Base.Bra_Strapless_FrillyPink"}, Price = 100 },
    { id = {"Base.Bra_Strapless_FrillyRed"}, Price = 100 },
    { id = {"Base.Bra_Strapless_RedSpots"}, Price = 100 },
    { id = {"Base.Bra_Strapless_Hide"}, Price = 100 },
    { id = {"Base.Bra_Strapless_White"}, Price = 100 },
    { id = {"Base.Bra_Straps_White"}, Price = 100 },
    { id = {"Base.Bikini_Pattern01"}, Price = 150 },
    { id = {"Base.Briefs_SmallTrunks_Black"}, Price = 200 },
    { id = {"Base.Briefs_SmallTrunks_Blue"}, Price = 200 },
    { id = {"Base.Briefs_SmallTrunks_Red"}, Price = 200 },
    { id = {"Base.Underpants_AnimalPrint"}, Price = 200 },
    { id = {"Base.FrillyUnderpants_Black"}, Price = 200 },
    { id = {"Base.Underpants_Black"}, Price = 200 },
    { id = {"Base.FrillyUnderpants_Pink"}, Price = 200 },
    { id = {"Base.FrillyUnderpants_Red"}, Price = 200 },
    { id = {"Base.Underpants_RedSpots"}, Price = 200 },
    { id = {"Base.Underpants_Hide"}, Price = 200 },
    { id = {"Base.Underpants_White"}, Price = 200 },
    -- ARMOR
    { id = {"Base.Hat_Beret"}, Price = 500 },
    { id = {"Base.Hat_BalaclavaFull"}, Price = 500 },
    { id = {"Base.Hat_Police"}, Price = 500 },
    { id = {"Base.Hat_Army"}, Price = 1000 },
    { id = {"Base.Hat_ArmyDesertNew"}, Price = 1000 },
    { id = {"Base.Hat_ArmyDesert"}, Price = 1000 },
    { id = {"Base.Hat_CrashHelmet_Police"}, Price = 1000 },
    { id = {"Base.Hat_RiotHelmet"}, Price = 1000 },
    { id = {"Base.Hat_ArmyWWII"}, Price = 1000 },
    { id = {"Base.Hat_SPHhelmet"}, Price = 1000 },
    { id = {"Base.ShinKneeGuard_L_Metal", "Base.ShinKneeGuard_R_Metal"}, Price = 1000 },
    { id = {"Base.Shoulderpad_Articulated_L_Metal", "Base.Shoulderpad_Articulated_R_Metal"}, Price = 1000 }, 
    { id = {"Base.Thigh_ArticMetal_R", "Base.Thigh_ArticMetal_L"}, Price = 1000 }, 
    { id = {"Base.ElbowPad_Right_Tactical"}, Price = 1000 },
    { id = {"Base.Vambrace_BodyArmour_Left_Army"}, Price = 1000 },
    { id = {"Base.GreaveBodyArmour_Right_Army"}, Price = 1000 },
    { id = {"Base.Shoes_ArmyBoots"}, Price = 1000 },
    { id = {"Base.Shoes_ArmyBootsDesert"}, Price = 1000 },
    { id = {"Base.Shoulderpad_MetalScrap_L", "Base.Shoulderpad_MetalScrap_R"}, Price = 1500 },
    { id = {"Base.Hat_GasMask_nofilter"}, Price = 1500 },
    { id = {"Base.Chainmail_SleeveFull_L", "Base.Chainmail_SleeveFull_R"}, Price = 2000 }, 
    { id = {"Base.Hat_GasMask"}, Price = 2000 },
    { id = {"Base.Vest_BulletArmy"}, Price = 5000 }, 
    { id = {"Base.Vest_BulletPolice"}, Price = 5000 }, 
    { id = {"Base.Vest_BulletSWAT"}, Price = 5000 },
    -- GOLD
    { id = {"Base.Medal_Bronze"}, Price = 100 },
    { id = {"Base.Medal_Gold"}, Price = 500 },
    { id = {"Base.Medal_Silver"}, Price = 250 },
    { id = {"Base.Necklace_Gold"}, Price = 600 },
    { id = {"Base.Necklace_GoldDiamond"}, Price = 800 },
    { id = {"Base.Necklace_GoldRuby"}, Price = 650 },
    { id = {"Base.Necklace_Silver"}, Price = 300 },
    { id = {"Base.Necklace_SilverCrucifix"}, Price = 250 },
    { id = {"Base.Necklace_SilverDiamond"}, Price = 150 },
    { id = {"Base.Necklace_SilverSapphire"}, Price = 200 },
    { id = {"Base.Necklace_YingYang"}, Price = 10 },
    { id = {"Base.NecklaceLong_Amber"}, Price = 50 },
    { id = {"Base.NecklaceLong_GoldDiamond"}, Price = 1000, },
    { id = {"Base.NecklaceLong_Gold"}, Price = 850, },
    { id = {"Base.NecklaceLong_SilverDiamond"}, Price = 450 },
    { id = {"Base.NecklaceLong_SilverEmerald"}, Price = 450 },
    { id = {"Base.NecklaceLong_SilverSapphire"}, Price = 450 },
    { id = {"Base.NecklaceLong_Silver"}, Price = 250 },
    { id = {"Base.NoseRing_Gold"}, Price = 100, },
    { id = {"Base.NoseRing_Silver"}, Price = 50 },
    { id = {"Base.NoseStud_Gold"}, Price = 80, },
    { id = {"Base.NoseStud_Silver"}, Price = 40 },
    { id = {"Base.Earring_Dangly_Diamond"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Emerald"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Pearl"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Ruby"}, Price = 100, },
    { id = {"Base.Earring_Dangly_Sapphire"}, Price = 100, },
    { id = {"Base.Earring_Stone_Emerald"}, Price = 100, },
    { id = {"Base.Earring_Stud_Gold"}, Price = 250, },
    { id = {"Base.Earring_LoopLrg_Gold"}, Price = 250, },
    { id = {"Base.Earring_LoopLrg_Silver"}, Price = 80 },
    { id = {"Base.Earring_LoopMed_Gold"}, Price = 100, },
    { id = {"Base.Earring_LoopMed_Silver"}, Price = 80 },
    { id = {"Base.Earring_Pearl"}, Price = 60, },
    { id = {"Base.Earring_Stone_Ruby"}, Price = 60, },
    { id = {"Base.Earring_Stone_Sapphire"}, Price = 60, },
    { id = {"Base.Earring_Stud_Silver"}, Price = 50 },
    { id = {"Base.Earring_LoopSmall_Gold_Both", "Base.Earring_LoopSmall_Gold_Top"}, Price = 50, },
    { id = {"Base.Earring_LoopSmall_Silver_Both", "Base.Earring_LoopSmall_Silver_Top"}, Price = 50, },
    { id = {"Base.Bracelet_BangleRightGold", "Base.Bracelet_BangleLeftGold"}, Price = 300 },
    { id = {"Base.Bracelet_BangleRightSilver", "Base.Bracelet_BangleLeftSilver"}, Price = 250 },
    { id = {"Base.Bracelet_ChainRightGold", "Base.Bracelet_ChainLeftGold"}, Price = 250 },
    { id = {"Base.Bracelet_ChainRightSilver", "Base.Bracelet_ChainLeftSilver"}, Price = 150 },
    { id = {"Base.WristWatch_Right_ClassicGold", "Base.WristWatch_Left_ClassicGold"}, Price = 1500 },
    { id = {"WristWatch_Right_Expensive", "Base.WristWatch_Left_Expensive"}, Price = 1500 },
    { id = {"Base.Ring_Right_MiddleFinger_GoldDiamond", "Base.Ring_Left_MiddleFinger_GoldDiamond", "Base.Ring_Right_RingFinger_GoldDiamond", "Base.Ring_Left_RingFinger_GoldDiamond"}, Price = 500 },
    { id = {"Base.Ring_Right_MiddleFinger_GoldRuby", "Base.Ring_Left_MiddleFinger_GoldRuby", "Base.Ring_Right_RingFinger_GoldRuby", "Base.Ring_Left_RingFinger_GoldRuby"}, Price = 500 },
    { id = {"Base.Ring_Right_MiddleFinger_Gold", "Base.Ring_Left_MiddleFinger_Gold", "Base.Ring_Right_RingFinger_Gold","Base.Ring_Left_RingFinger_Gold"}, Price = 500 },
    { id = {"Base.Ring_Right_MiddleFinger_SilverDiamond", "Base.Ring_Left_MiddleFinger_SilverDiamond", "Base.Ring_Right_RingFinger_SilverDiamond", "Base.Ring_Left_RingFinger_SilverDiamond"}, Price = 300 },
    { id = {"Base.Ring_Right_MiddleFinger_Silver", "Base.Ring_Left_MiddleFinger_Silver", "Base.Ring_Right_RingFinger_Silver", "Base.Ring_Left_RingFinger_Silver"}, Price = 300 },
    { id = {"Base.BellyButton_DangleGoldRuby"}, Price = 150 },
    { id = {"Base.BellyButton_DangleGold"}, Price = 250 },
    { id = {"Base.BellyButton_DangleSilverDiamond"}, Price = 150 },
    { id = {"Base.BellyButton_DangleSilver"}, Price = 50 },
    { id = {"Base.BellyButton_RingGoldDiamond"}, Price = 150 },
    { id = {"Base.BellyButton_RingGoldRuby"}, Price = 150 },
    { id = {"Base.BellyButton_RingGold"}, Price = 250 },
    { id = {"Base.BellyButton_RingSilverAmethyst"}, Price = 75 },
    { id = {"Base.BellyButton_RingSilverDiamond"}, Price = 75 },
    { id = {"Base.BellyButton_RingSilverRuby"}, Price = 75 },
    { id = {"Base.BellyButton_RingSilver"}, Price = 50 },
    { id = {"Base.BellyButton_StudGoldDiamond"}, Price = 150 },
    { id = {"Base.BellyButton_StudGold"}, Price = 150 },
    { id = {"Base.BellyButton_StudSilverDiamond"}, Price = 75 },
    { id = {"Base.BellyButton_StudSilver"}, Price = 50 }
}

PZLinuxTradingCompanyNameTable = {
    { name = "Crisis Commerce Corp", code = "CCC", price = 1450 },
    { name = "Umbrella Corp", code = "AC", price = 1400 },
    { name = "Walker & Crawler", code = "WC", price = 1300 },
    { name = "Survival Solutions Inc", code = "SSI", price = 1200 },
    { name = "Reclaim Resources Ltd", code = "RRL", price = 1110 },
    { name = "Brain Beers Times", code = "BBT", price = 1000 },
    { name = "Zom Bin", code = "ZB", price = 950 },
    { name = "Endurance Equipments", code = "EE", price = 850 },
    { name = "Grinning Grim Goods", code = "GGG", price = 610 },
    { name = "Country Court Outlaw", code = "CCO", price = 580 },
    { name = "ZomboTrade Co", code = "ZTC", price = 560 },
    { name = "COVID Pop Ltd", code = "CPL", price = 500 },
    { name = "Gorrest Fump", code = "GF", price = 450 },
    { name = "Phoenix Resupply Corp", code = "PRC", price = 350 },
    { name = "Heaven Saint Christ", code = "HSC", price = 260 },
    { name = "28 Ways to Stay Safe", code = "WSS", price = 245 },
    { name = "The Hunger Z", code = "THZ", price = 235 },
    { name = "Zombie of the rings", code = "ZOR", price = 220 },
    { name = "Zombie Zumba", code = "ZZ", price = 200 },
    { name = "Indoor Adventures", code = "IA", price = 180 },
    { name = "Pandemic Pills Inc", code = "PPI", price = 170 },
    { name = "Aftermath Trading Post", code = "ATP", price = 160 },
    { name = "Waste Not Industries", code = "WNI", price = 120 },
    { name = "NecroTech Innovations", code = "NTI", price = 80 },
    { name = "Z Max", code = "ZM", price = 65 },
    { name = "Vigilant Ventures", code = "VV", price = 40 },
    { name = "Flee Market", code = "FM", price = 30 },
    { name = "Raven Goods & Supply", code = "RGS", price = 25 },
    { name = "Brains & Bargains", code = "BB", price = 20 },
    { name = "Rot & Roll", code = "RR", price = 10 },
    { name = "Butcher Ltd", code = "BL", price = 5 }
}