local root = arg[1] or "."
local luaRoot = root .. "/Contents/mods/B42 PZLinux/42/media/lua"

local function PZLinuxTestAssert(condition, message)
    if not condition then error(message, 2) end
end

local function PZLinuxTestRead(path)
    local file = assert(io.open(path, "rb"))
    local content = file:read("*a")
    file:close()
    return content
end

rawset(_G, "ZombRand", function(_minimum, maximum)
    if maximum == nil then return 0 end
    return maximum - 1
end)

PZLinuxDarkWebItemsTable = {}
dofile(luaRoot .. "/shared/PZLinux/PZLinuxConfig.lua")
dofile(luaRoot .. "/shared/PZLinux/PZLinuxEconomy.lua")
dofile(luaRoot .. "/shared/PZLinux/PZLinuxContractsData.lua")
dofile(luaRoot .. "/shared/PZLinux/PZLinuxMissionLocations.lua")
dofile(luaRoot .. "/shared/PZLinux/PZLinuxContractRequestData.lua")
dofile(luaRoot .. "/shared/PZLinux/PZLinuxContractMission.lua")

local cityByContract = { [2] = 3, [3] = 3, [7] = 3, [8] = 2 }
for _, definition in ipairs(PZLinuxContractDefinitions) do
    local mission, missionError = PZLinuxContractsBuildMission({
        id = definition.id,
        code = "TEST",
        questName = definition.questName,
        cityId = cityByContract[definition.id] or 0,
        difficulty = definition.difficulty,
        reward = definition.reward,
    })
    PZLinuxTestAssert(mission ~= nil, "contract " .. tostring(definition.id) .. " failed: " .. tostring(missionError))
    PZLinuxTestAssert(mission.note ~= "" and mission.fullNote ~= "", "contract " .. tostring(definition.id) .. " has no canonical note")
end

local killMission = assert(PZLinuxContractsBuildMission({
    id = 1, code = "CCC", questName = "Kill zombies", cityId = 0, difficulty = 1, reward = 750,
}))
PZLinuxTestAssert(killMission.zombieToKill == 50, "kill count must be generated by the authority")
PZLinuxTestAssert(killMission.reward == 5750, "kill reward must be derived from the generated count")
PZLinuxTestAssert(killMission.fullNote:find("%* Zombies killed: 0 / 50"),
    "kill contract note must show initial progress and its server-generated target")
PZLinuxTestAssert(killMission.fullNote:sub(1, 1) == "*"
    and not killMission.fullNote:find("All around the world", 1, true),
    "a location-free contract note must not contain the legacy empty location header")
PZLinuxTestAssert(PZLinuxContractsSetKillProgress(killMission.fullNote, 1, 50):find("%* Zombies killed: 1 / 50"),
    "kill contract note progress must remain readable after the first kill")
PZLinuxTestAssert(PZLinuxContractsSanitizeNoteText(":\n* \n* [CCC] Kill zombies")
        == "* [CCC] Kill zombies",
    "legacy contract notes must lose their stray empty location lines")
PZLinuxTestAssert(PZLinuxContractsCanonicalActiveState("in_progress") == 1,
    "the first kill must keep the contract active")
PZLinuxTestAssert(PZLinuxContractsCanonicalActiveState("ready_to_complete") == 9,
    "only a completed kill objective may unlock contract payment")

local packageMission = assert(PZLinuxContractsBuildMission({
    id = 2, code = "AC", questName = "Retrieve the package", cityId = 3, difficulty = 3, reward = 4000,
}))
PZLinuxTestAssert(packageMission.locationPool == "packages", "package contract must use the package pool")
PZLinuxTestAssert(packageMission.locationId == "pkg_brandenburg_middle_school_01", "location must come from the configured city pool")
PZLinuxTestAssert(packageMission.locationX == 2076 and packageMission.locationY == 6181, "location coordinates must be canonical")

local autoMission = assert(PZLinuxContractsBuildMission({
    id = 5, code = "WC", questName = "Send automobile parts", cityId = 0, difficulty = 2, reward = 1800,
}))
PZLinuxTestAssert(autoMission.info == "Base.CarBattery3", "auto part must come from the allowlist")
PZLinuxTestAssert(autoMission.infoCount == 1 and autoMission.reward == 1800, "auto request count and reward must be canonical")

local medicalMission = assert(PZLinuxContractsBuildMission({
    id = 9, code = "SSI", questName = "Send medical equipment", cityId = 0, difficulty = 2, reward = 2200,
}))
PZLinuxTestAssert(medicalMission.info == "Base.Bandaid", "medical item must come from the allowlist")
PZLinuxTestAssert(medicalMission.infoCount == 10 and medicalMission.reward == 1100, "medical count and reward must be server generated")

local weaponMission = assert(PZLinuxContractsBuildMission({
    id = 10, code = "RRL", questName = "Send weapons", cityId = 0, difficulty = 3, reward = 4500,
}))
PZLinuxTestAssert(weaponMission.info == "Base.Pistol3", "weapon must come from the allowlist")
PZLinuxTestAssert(weaponMission.infoCount == 5 and weaponMission.reward == 1350, "weapon count and reward must be server generated")

local variablesPath = luaRoot .. "/shared/ISPZLinuxVariablesTables.lua"
local variables = PZLinuxTestRead(variablesPath)
local acceptBlock = variables:match("function PZLinuxContractsApplyAccept.-\nend\n\nfunction PZLinuxContractsApplyCancel")
PZLinuxTestAssert(acceptBlock ~= nil, "could not inspect PZLinuxContractsApplyAccept")
local cancelBlock = variables:match("function PZLinuxContractsApplyCancel.-\nend\n\nfunction PZLinuxContractsBagContainsCorpse")
local completeBlock = variables:match("function PZLinuxContractsApplyComplete.-\nend\n\nfunction PZLinuxContractsAcknowledgeCompletion")
PZLinuxTestAssert(cancelBlock and not cancelBlock:find("PZLinuxUIOpenMenu", 1, true),
    "server-side contract cancellation must not open or replace a client UI")
PZLinuxTestAssert(completeBlock and not completeBlock:find("PZLinuxUIOpenMenu", 1, true),
    "server-side contract completion must not open a second contracts UI")

local forbiddenFields = {
    "reward", "code", "questName", "cityId", "locationX", "locationY", "locationZ",
    "info", "infoCount", "zombieToKill", "note",
}
for _, field in ipairs(forbiddenFields) do
    PZLinuxTestAssert(not acceptBlock:find("state%." .. field), "accept reads forged client field state." .. field)
end

local requestBlock = variables:match("function PZLinuxRequestContractAccept.-\nend\n\nfunction PZLinuxRequestContractCancel")
PZLinuxTestAssert(requestBlock ~= nil, "could not inspect PZLinuxRequestContractAccept")
PZLinuxTestAssert(requestBlock:find("local state = { requestId = requestId, contractId = tonumber%(contractId%) }", 1, false) ~= nil,
    "accept request must contain only requestId and contractId")
PZLinuxTestAssert(acceptBlock:find("contractPickUp = modData%.PZLinuxContractPickUp"),
    "accept response must synchronize the package objective flag")
PZLinuxTestAssert(acceptBlock:find("PZLinuxContractsRemoveBoardContract%(contractId, boardData%.generatedHour%)"),
    "accepting a contract must consume its offer from the current server board")
PZLinuxTestAssert(acceptBlock:find("PZLinuxContractsReplaceContractNote%(playerObj, worldRecord%)"),
    "the server must create the persistent contract note during acceptance")
PZLinuxTestAssert(variables:find("item:seePage%(1%) == expectedText"),
    "contract synchronization must repair a stale server-owned note")
PZLinuxTestAssert(variables:find("playerZombieKills = playerObj%.getZombieKills"),
    "contract acceptance must snapshot the authoritative player zombie-kill counter")
PZLinuxTestAssert(variables:find("function PZLinuxContractsReconcilePlayerZombieKills"),
    "the server must reconcile multiplayer zombie kills from the player kill counter")
PZLinuxTestAssert(variables:find("pendingZombieKillCredits = 0")
    and variables:find("absorbedKills = math%.min%(observedKills, pendingCredits%)"),
    "direct server death events and delayed kill-counter updates must not double-credit a zombie")
PZLinuxTestAssert(variables:find("boardGeneratedHour = tonumber%(mission%.boardGeneratedHour%) or 0"),
    "world contracts must retain the board generation they came from")
PZLinuxTestAssert(variables:find("PZLinuxContractsPruneConsumedBoardContracts%(boardData%)"),
    "the board must prune offers already consumed during its current generation")
PZLinuxTestAssert(variables:find("function PZLinuxContractsAdminForceBoard")
    and variables:find('error = "admin_required"')
    and variables:find("adminForcedContracts"),
    "forcing a test contract must be server-authorized and survive normal board pruning")
PZLinuxTestAssert(variables:find("boardRefreshHours")
    and variables:find("needsScheduleMigration")
    and variables:find("boardData%.scheduleVersion = scheduleVersion"),
    "the weekly board must migrate legacy schedules and refresh from the real world hour")
PZLinuxTestAssert(not variables:find("if worldHour < 168 then worldHour = 168 end", 1, true),
    "new worlds must not delay their first weekly board refresh until day fourteen")

local contextMenu = PZLinuxTestRead(luaRoot .. "/client/Context/World/ISContextContractsMenu.lua")
PZLinuxTestAssert(contextMenu:find('tonumber%(worldRecord%.contractId%) == 2'),
    "package context menu must recover objective state from the persistent world contract")
PZLinuxTestAssert(contextMenu:find('PZLinuxContractsIsRecordStatus%(worldRecord, "accepted", "in_progress"%)'),
    "package context menu must only recover an actionable persistent objective")
PZLinuxTestAssert(variables:find('function PZLinuxContractsGetActiveState'),
    "server-authoritative active contract synchronization must exist")
local syncBlock = variables:match("function PZLinuxContractsGetActiveState.-\nend\n\nfunction PZLinuxContractsSetTypeFlags")
PZLinuxTestAssert(syncBlock and syncBlock:find('record.status == "completed"'),
    "completed world-contract history must not be restored as an active player contract")
PZLinuxTestAssert(syncBlock and syncBlock:find('record.status == "cancelled"'),
    "cancelled world-contract history must not be restored as an active player contract")
PZLinuxTestAssert(syncBlock and syncBlock:find("completionReceipt = pzlinux%.contracts"),
    "contract synchronization must expose a persistent unread completion receipt")
local linuxMenu = PZLinuxTestRead(luaRoot .. "/client/Context/World/ISContextLinuxMenu.lua")
local closeBlock = linuxMenu:match("function linuxUI:onCloseX.-\nend")
PZLinuxTestAssert(closeBlock and closeBlock:find("PZLinuxRequestContractSync"),
    "closing the computer must synchronize the active contract")
PZLinuxTestAssert(not contextMenu:find("Synchronize active contract"),
    "contract synchronization must not leak into the player context menu")
PZLinuxTestAssert(contextMenu:find("PZLinuxContractsMaybeSyncContext"),
    "opening the contract context menu must perform a throttled silent resynchronization")
PZLinuxTestAssert(contextMenu:find("legacyPackageFallback"),
    "legacy package contracts must remain actionable when their client type flag is missing")
PZLinuxTestAssert(contextMenu:find("%[PZLinux Contracts Context%] option missing"),
    "missing package actions must emit actionable diagnostics")
PZLinuxTestAssert(variables:find('command == "PZLinuxContractDepositResult"'),
    "mailbox deposit results must synchronize the next contract stage")

for _, helperName in ipairs({
    "PZLinuxContractsGiveContractCase",
    "PZLinuxContractsGiveMailCorpseBag",
    "PZLinuxContractsGiveBloodJar",
}) do
    local helperBlock = variables:match("function " .. helperName .. ".-\nend")
    PZLinuxTestAssert(helperBlock and helperBlock:find("PZLinuxSyncAddedInventoryItem"),
        helperName .. " must synchronize server-created inventory items")
end

local depositBlock = variables:match("function PZLinuxContractsApplyDeposit.-\nend")
PZLinuxTestAssert(depositBlock and depositBlock:find("PZLinuxRemoveInventoryItem"),
    "mailbox deposits must synchronize removal of delivered contract items")
PZLinuxTestAssert(variables:find("sendRemoveItemFromContainer%(container, item%)"),
    "server inventory removals must be sent to the owning client")
PZLinuxTestAssert(contextMenu:find("packageInteractionRadius%) or 5"),
    "package context interactions must keep the five-tile fallback radius")

local contractEvents = PZLinuxTestRead(luaRoot .. "/client/Context/World/Events/PZLinuxOnEvents.lua")
PZLinuxTestAssert(contractEvents:find("PZLinux%.ContractCompletionNotifications%[notificationKey%] == true"),
    "contract completion feedback must be idempotent across server synchronization")
PZLinuxTestAssert(contractEvents:find("modData%.PZLinuxActiveContract = 10"),
    "a synchronized completed contract must still expose the payment state locally")
PZLinuxTestAssert(contractEvents:find("if alreadyNotified then return end"),
    "repeated contract synchronization must not replay completion feedback")

local contractsUi = PZLinuxTestRead(luaRoot .. "/client/Context/World/Features/PZLinuxContracts.lua")
PZLinuxTestAssert(not contractsUi:find("AddItem%(['\"]Base%.Note['\"]%)"),
    "the client must not create a private duplicate of the server contract note")
PZLinuxTestAssert(contractsUi:find("PZLinuxContractsLocalizedItemName"),
    "item-request contracts must resolve names through the local PZ translation catalog")
PZLinuxTestAssert(contractsUi:find("tonumber%(contractPreview%.infoCount%) or 0"),
    "item-request contracts must use the immutable server preview quantity")
PZLinuxTestAssert(not contractsUi:find("tostring%(dialogue%.modData%.PZLinuxContractInfoCount%)"),
    "contract dialogue must not read a transient ModData quantity that can become nil")
local stateRenderBlock = contractsUi:match("function contractsUI:showSynchronizedContractState.-\nend\n\n%-%- INIT")
PZLinuxTestAssert(stateRenderBlock and stateRenderBlock:find("activeContract == 1"),
    "the contracts UI must render an active contract after server synchronization")
PZLinuxTestAssert(stateRenderBlock and stateRenderBlock:find("activeContract == 9 or activeContract == 10"),
    "the contracts UI must expose payment for a server-completed contract")
PZLinuxTestAssert(stateRenderBlock and stateRenderBlock:find("PZLinuxRequestContractsBoard"),
    "the contracts UI may request fresh offers only after checking synchronized active state")
PZLinuxTestAssert(contractsUi:find("PZLinuxContractsShowCompletionReceipt"),
    "the contracts UI must render the authoritative completion receipt")
local receiptBlock = contractsUi:match("local function PZLinuxContractsShowCompletionReceipt.-\nend\n\nlocal function PZLinuxContractsStopDialogue")
PZLinuxTestAssert(receiptBlock and receiptBlock:find("PZLinuxContractsCompletionAmountText%(receipt%)"),
    "the translated completion receipt must display the authoritative credited amount")
PZLinuxTestAssert(contractsUi:find("receipt%.moneyEarned or receipt%.amount")
    and contractsUi:find('return label %.%. " " %.%. tostring%(amount%) %.%. " %$"'),
    "the receipt amount must remain visible outside the rich-text dollar prefix")
PZLinuxTestAssert(contractsUi:find("PZLinuxFormatText%(key, fallback, %.%.%.%)"),
    "contract translations must use the shared placeholder-safe formatter")
PZLinuxTestAssert(contractsUi:find("PZLinuxRequestContractCompletionAck"),
    "the completion receipt must be acknowledged only after rendering")
PZLinuxTestAssert(variables:find("pzlinux%.contracts%.pendingCompletion = completionReceipt"),
    "the server must persist a completion receipt before clearing contract state")
PZLinuxTestAssert(variables:find("moneyEarned = moneyEarned"),
    "the persisted completion receipt must expose an unambiguous earned-money field")
PZLinuxTestAssert(variables:find("function PZLinuxContractsAcknowledgeCompletion"),
    "the server must expose a receipt acknowledgement validator")
local serverCommands = PZLinuxTestRead(luaRoot .. "/server/PZLinuxServerCommands.lua")
PZLinuxTestAssert(serverCommands:find(
    "PZLinuxServerForEachOnlinePlayer%(PZLinuxContractsReconcilePlayerZombieKills%)"
), "the server must periodically reconcile kills even when OnZombieDead has no attacker")
PZLinuxTestAssert(serverCommands:find(
    "PZLinuxContractCompletionAck = PZLinuxServerContractCompletionAck",
    1,
    true
), "the prefixed completion-receipt acknowledgement command must be registered")
PZLinuxTestAssert(serverCommands:find(
    "PZLinuxContractAdminForce = PZLinuxServerContractAdminForce",
    1,
    true
), "the admin-only forced-contract command must be registered with a PZLinux prefix")
local debugMenu = PZLinuxTestRead(luaRoot .. "/client/Context/World/ISContextDebug.lua")
PZLinuxTestAssert(debugMenu:find("local function PZLinuxDebugForceContract%(player, contractId%)")
    and debugMenu:find("PZLinuxDebugHasAdminAccess")
    and debugMenu:find("isDebugEnabled and isDebugEnabled%(%)")
    and debugMenu:find("if isClient and isClient%(%) then")
    and debugMenu:find("PZLinuxRequestAdminForceContract")
    and debugMenu:find("Force contract on board", 1, true),
    "MP administrators and solo debug sessions must have a contract test menu")
local initialiseBlock = contractsUi:match("function contractsUI:initialise.-\nend\n\nfunction contractsUI:onCancelContract")
PZLinuxTestAssert(initialiseBlock and initialiseBlock:find("PZLinuxRequestContractSync"),
    "opening the contracts UI must synchronize with the server before rendering")
PZLinuxTestAssert(contractsUi:find("Events%.OnTickEvenPaused or Events%.OnTick"),
    "contract dialogues must continue while the game is paused")
PZLinuxTestAssert(contractsUi:find("self%.updateCoroutineFunc%(%)\n    if self%.updateCoroutineFunc"),
    "contract dialogues must be primed immediately before tick registration")
PZLinuxTestAssert(not contractsUi:find("table%.remove%(selectedContracts"),
    "previewing a contract must not consume the client-side offer")
PZLinuxTestAssert(contractsUi:find("PZLinux contract preview error:"),
    "contract preview failures must not leave a silent empty screen")
PZLinuxTestAssert(contractsUi:find("playerName = PZLinuxFormatIRCName")
    and contractsUi:find("sellerName = PZLinuxFormatIRCName"),
    "inline contract dialogues must use rich-text-safe IRC sender names")
local contractDialogue = PZLinuxTestRead(luaRoot .. "/client/Context/World/Contracts/PZLinuxContractDialogue.lua")
PZLinuxTestAssert(contractDialogue:find("playerName = PZLinuxFormatIRCName")
    and contractDialogue:find("sellerName = PZLinuxFormatIRCName"),
    "external contract dialogues must use rich-text-safe IRC sender names")
local utils = PZLinuxTestRead(luaRoot .. "/client/Context/World/Features/PZLinuxUtils.lua")
PZLinuxTestAssert(utils:find('return "%[" %.%. name %.%. "%] "'),
    "IRC sender names must use visible brackets instead of rich-text tags")

local boardRefreshBlock = variables:match("function PZLinuxContractsGetBoardData.-\nend\n\nfunction PZLinuxContractsGetBoard")
PZLinuxTestAssert(boardRefreshBlock and not boardRefreshBlock:find("PZLinuxContractsClearState"),
    "refreshing server offers must never clear an accepted player contract")

local inlineIntros = {
    [2] = "RetrievePackage_Intro",
    [3] = "Manhunt_Intro",
    [4] = "BloodAnalysis_Intro",
    [5] = "AutoParts_Intro",
    [6] = "CaptureZombie_Intro",
    [7] = "Cargo_Intro",
    [8] = "Protect_Intro",
    [9] = "Medical_Intro",
    [10] = "Weapons_Intro",
}
for contractId, introName in pairs(inlineIntros) do
    local startMarker = "elseif contract == " .. tostring(contractId) .. " then"
    local startAt = assert(contractsUi:find(startMarker, 1, true), "missing UI branch for contract " .. tostring(contractId))
    local introAt = assert(contractsUi:find(introName, startAt, true), "missing intro for contract " .. tostring(contractId))
    local openingBlock = contractsUi:sub(startAt, introAt)
    PZLinuxTestAssert(not openingBlock:find("PZLinuxContractsWaitDialogue", 1, true),
        "contract " .. tostring(contractId) .. " waits before displaying its intro")
end

for contractId, filename in pairs({
    [1] = "PZLinuxKillZombies.lua",
    [11] = "PZLinuxSendComputer.lua",
    [12] = "PZLinuxSendFridge.lua",
}) do
    local externalDialogue = PZLinuxTestRead(luaRoot .. "/client/Context/World/Contracts/" .. filename)
    local introAt = assert(externalDialogue:find("_Intro", 1, true), "missing intro for contract " .. tostring(contractId))
    PZLinuxTestAssert(not externalDialogue:sub(1, introAt):find("PZLinuxContractDialogue.wait", 1, true),
        "contract " .. tostring(contractId) .. " waits before displaying its intro")
end

print("PZLinux contract authority tests OK")
